### ISSUE TITLE
[Bug] Sessions aren't persistent

### ISSUE THREAD

**Issue by Rigerhit047** [SpikeHD/Dorion#100]
**Describe the bug**
For some reason the sessions aren't persistent on the program.

**To Reproduce**
1. Open Dorion.
2. Login with your account(s).
3. Close/Restart the app or turn off the PC.
4. Open Dorion again.

**Expected behavior**
Being able to succesfully login without inputting email and password again.

**Screenshots**
![imagen](https://github.com/SpikeHD/Dorion/assets/87140051/3d797867-9fcd-40e1-90e6-98e06989a40a)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: v1.2.0

**Additional context**

- I am able to keep my sessions on the official Discord client (and canary), Armcord, Firefox and Vencord Desktop without issue.

- Since I have to login again everytime, I end up with LOTS of devices on the devices section of settings, it doesn't count like the session ended in them.

**Comment by SpikeHD** [comment]
I get that issue while developing sometimes, usually because I'm switching between browser logins and such while testing things, are you switching platforms/between different logins frequently?

**Comment by Rigerhit047** [comment]
If you mean like changing accounts on my PC or switching to use other Discord clients or browser, then no. I use Discord in my phone a lot, but I do not log off and log in in it and change accounts very rarely (and even then since it happens just restarting the app I wouldn't have time to do so)

**Comment by SpikeHD** [comment]
Odd, I don't think many others have had issues with sessions expiring often like that so I have to imagine there is something different you're doing that most don't. Seeing as those sessions are *expiring* rather than just *disappearing* means your cache isn't mysteriously being deleted, so unfortunately I don't really have a solution for you right now

**Comment by Rigerhit047** [comment]
Damn, tha's sad, I do not know what different I could be doing, since other third party clients (and the official ofc) work fine... I tried searching if it was a setting on Edge for some reason but then I saw that WebView and the browser itself were two separate things and the configuration of WebView worked differently, so since I obviously didn't touch any of that then I have no clue of what it would be..

**Comment by SpikeHD** [comment]
If I could give some sort of advice I would, but unfortunately Dorion should (and does) function identically in this regard to the official web client, so idk :P

Unless any new info comes to light or someone else is able to repro, I'll close this in the next couple days
