### ISSUE TITLE
[Feature Request] Increase/remove account switcher limit

### ISSUE THREAD

**Issue by trinkey** [SpikeHD/Dorion#101]
Normal discord, both desktop app and web version (mobile app doesn't have account switcher), the limit for the amount of accounts you can add onto the account switcher is 5.

![image](https://github.com/SpikeHD/Dorion/assets/97406176/2d66499f-14e7-46df-bb1e-00dce2ff614f)

This should just be a frontend software limitation, as the accounts are stored in an array in localStorage, however manually changing the localStorage to add more accounts (I've tried) doesn't work, it just removes any extra accounts.

I have quite a few (definetely not 11) accounts and it would be great to be able to switch between them without switching between discord (5), firefox (5 more), and chrome (my last one) to access my accounts.

**Comment by Banaanae** [comment]
Workaround is making a new Dorion profile, which allows for another 5 accounts
![image](https://github.com/SpikeHD/Dorion/assets/83927639/a4d49123-fac7-4dcf-9f42-b28235843d5d)

**Comment by SpikeHD** [comment]
I don't think I plan on implementing this in Dorion specifically, but you can open an issue in [my shelter-plugins repo](https://github.com/SpikeHD/shelter-plugins) or in like, the Vencord repo, if you use that, whatever you prefer. But like mentioned above there *is* the Dorion profiles workaround you can use.
