### ISSUE TITLE
[Bug] Out of memory

### ISSUE THREAD

**Issue by Scrapper1824** [SpikeHD/Dorion#103]
give out of memory after a little use and i have plenty of ram so is there a memory limiter

![Screenshot (51)](https://github.com/SpikeHD/Dorion/assets/72410525/bc5ca568-504a-45ef-b668-751183b623a5)

**Comment by SpikeHD** [comment]
What are you computers specifications? Can you keep track of Dorions memory usage and let me know if it steadily increases until it crashes or something?

**Comment by Scrapper1824** [comment]
yea i will

**Comment by Small-Ku** [comment]
I also met this when my emulators told me that my GPU driver is crashed

**Comment by SpikeHD** [comment]
Since I haven't experienced this ever, and it seems to be due to things happening elsewhere on the system, it's not really something I can just "fix", so I will close this unless others can provide specific details (especially details that show that it is some fault of Dorion itself)
