### ISSUE TITLE
[Bug] macOS permission request spam

### ISSUE THREAD

**Issue by jacksongoode** [SpikeHD/Dorion#104]
**Describe the bug**
Unable to join the room, stalls at RTC connecting.

There are four permission requests when joining a VC. I understand for the first time having to confirm, but it seems like the permission doesn't save beyond the session.

**To Reproduce**
Join a VC on macOS.

**System Info (please complete the following information):**
 - OS: macOS 13.5
 - Version: 1.2.1

**Comment by jacksongoode** [comment]
1.3.0 hasn't resolved this issue either.

**Comment by jacksongoode** [comment]
Just an update, still experiencing this in 2.0.0, macOS.

**Comment by SpikeHD** [comment]
Shoot, I had it at one point while working on v2 before, I think it's just a permissions problem now though

**Comment by SpikeHD** [comment]
Okay this is dumb, but can you try the following:
1. Open Dorion
2. Open "Voice & Video" settings
3. Click through the permission request spam
4. Close settings, join VC
5. Click through more permission request spam

This seemed to properly connect me to VC. Obviously not a *good* solution and I would like see it *not* spam, but if VC is a priority for you it should at least be an option.

**Comment by jacksongoode** [comment]
Ah it does connect now. It's just that each time Dorion starts, 3 permission requests need to be clicked through in order to join.

**Comment by SpikeHD** [comment]
Sweet, glad it's at least an option, I'll try to investigate getting rid of the copious amounts of permission requests

**Comment by SpikeHD** [comment]
Fixed in f67deae and will be available in the next release (coming in a few hours probs)

**Comment by SpikeHD** [comment]
Nvm, apparently it only got fixed in debug builds??

**Comment by SpikeHD** [comment]
Aha! I found it! Apparently, universal bundles have a bug where architecture-specific bundles do not (see: https://github.com/tauri-apps/tauri/issues/8041). I will release individual ARM and x86 DMGs separately until this is resolved, which fixes the issue.

**Comment by jacksongoode** [comment]
Worked, thanks!
