### ISSUE TITLE
[Bug] Popout stream don't work

### ISSUE THREAD

**Issue by Dysta** [SpikeHD/Dorion#105]
**Describe the bug**
When someone share its screen in a VC, you can't popout the stream.

**To Reproduce**
Join a VC with someone sharing its screen
Click on the popout button
Nothing happen

**Expected behavior**
A new window with the stream inside

**Screenshots**
-

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: 1.2.1
 - Any other relevant info: 

**Additional context**

**Comment by Banaanae** [comment]
The error:
![image](https://github.com/SpikeHD/Dorion/assets/83927639/fc0964bf-9f5b-485b-b8e6-6a4afd804dfb)

**Comment by SpikeHD** [comment]
This should be fixed as of 63ff555
