### ISSUE TITLE
[Bug] Vencord settings buttons don't work

### ISSUE THREAD

**Issue by Banaanae** [SpikeHD/Dorion#107]
**Describe the bug**
The donate, Open QuickCSS and Open in GitHub buttons don't work and throw errors when pressed

**To Reproduce**
1. Open settings and click on Vencord
2. Press any of the buttons listed above
3. See error (posted in screenshots)

**Expected behavior**
Donate and Open in GitHub buttons should open their respective site (with _blank)
Open QuickCSS should open the QuickCSS editor

**Screenshots**
Donate AND Open in GitHub button:
![image](https://github.com/SpikeHD/Dorion/assets/83927639/237e4208-d9e3-4720-ac4c-545db41125e0)

Open QuickCSS button:
![image](https://github.com/SpikeHD/Dorion/assets/83927639/1a698512-a764-47ed-83cc-4e94d8de542a)
Expanded
![image](https://github.com/SpikeHD/Dorion/assets/83927639/c6ae4a93-174a-4712-9418-aa3186da2b6a)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.2.1
 - Any other relevant info: 

**Additional context**
Vencord cloud buttons may also not work, didn't test because I don't use it

All other vencord buttons where tested and didn't have any issues

Likely related to #105, involving making new windows

**Comment by SpikeHD** [comment]
While the QuickCSS button is a more involved issue, the Donate and GitHub buttons were fixed in f4edc0c638f146bbd1e2242fcab6ca02a571335d
