### ISSUE TITLE
[Bug] shows this error when i open vencord plugins

### ISSUE THREAD

**Issue by LhymeFruit** [SpikeHD/Dorion#108]
**Describe the bug**
ive reinstalled twice and it works unless i restart dorion then it doesnt work. the vencord plugins do work but i can acsess the plugin tabs

**To Reproduce**
open plugins

**Expected behavior**
it shows the plugins

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/53196094/cfd22302-b52f-434b-82f7-0050cf4198dd)

**System Info (please complete the following information):**
 - OS: windows 10 
 - Version: 22h2
 - Any other relevant info: 

**Additional context**

**Comment by luximus-hunter** [comment]
Version should be Dorion version 😉

Other than that you can try to export settings and then clear out the web/userdata cache

**Comment by SpikeHD** [comment]
This works totally fine on my end, so you should make sure you're on the latest version as well as doing everything above ^
