### ISSUE TITLE
[Bug] RNNoise plugin not working

### ISSUE THREAD

**Issue by Drake356** [SpikeHD/Dorion#109]
**Describe the bug**
Describe the problem here.
When I enable RNNoise suppression my microphone stops being detected or working at all.
**To Reproduce**
Log in, add the RNNoise plugin, give mic permissions, join voice chat, enable noise suppression.
**Expected behavior**
Describe what should be expected here.
My mic should work :<!
**Screenshots**

**System Info (please complete the following information):**
 - OS: [e.g. Windows 11, Ubuntu 22.04]
 - Version: [e.g. v1.2.1]
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
This is already a known issue, see #38
