### ISSUE TITLE
[Feature Request] Custom RPC detectables

### ISSUE THREAD

**Issue by Small-Ku** [SpikeHD/Dorion#110]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my games are not detected by the rsRPC. and I found that it only detects games that in https://raw.githubusercontent.com/OpenAsar/arrpc/main/src/process/detectable.json

**Describe the solution you'd like**
A setting menu that let user register their games and show all games that are detected by rsRPC before.

**Describe alternatives you've considered**
A additional detectable JSON file that would be added to launch rsRPC.

**Additional context**
What Discord did:
![A screenshot of Discord's Registered Games menu](https://github.com/SpikeHD/Dorion/assets/16464896/d3c8b4b3-a512-4e37-a093-842a74ffc95e)

**Comment by SpikeHD** [comment]
This is almost done, just leaving a TODO for myself:

* [ ] Remove detectable games
* [ ] Check for, and overwrite, repeated custom detectable
* [ ] Wipe custom detectable games if corrupt

Demo of what is done if you're curious

https://github.com/SpikeHD/Dorion/assets/25207995/024af999-d9eb-4270-b6a1-b9559e1cc520

**Comment by SpikeHD** [comment]
while it's still somewhat experimental, I'm considering this done as of v2.3.0
