### ISSUE TITLE
[Bug] Block Discord Telemetry doesn't do anything

### ISSUE THREAD

**Issue by Banaanae** [SpikeHD/Dorion#112]
**Describe the bug**
Vencord added the required plugin "NoTrack" which blocks discord telemetry and can't be turned off

**To Reproduce**
1. Go to the plugins tab under vencord
2. Search NoTrack
3. See it's forced on (and can't be turned off)

**How to fix**
There are a few options
1. Remove the toggle in dorion settings and make the plugin not required
2. Remove the toggle in dorion settings
3. Remove the plugin

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/83927639/944495c9-3b73-431b-9510-7de128cc437d)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.2.1
 - Any other relevant info: Running bleeding edge vencordorion, tested on vanilla

**Comment by luximus-hunter** [comment]
I hope you realise that disabling that plugin will make Discord be able to see you're doing desktop stuff in a browser. Aka using a modded client.

There is a reason it's on, and forced on

**Comment by Banaanae** [comment]
> I hope you realise that disabling that plugin will make Discord be able to see you're doing desktop stuff in a browser. Aka using a modded client.
> 
> There is a reason it's on, and forced on

I know, currently in dorion settings it has the block telemetry option (which was added before NoTrack) which is off by default. So if spike wanted the option to toggle it, it would be available  in options 1 and 3

And option 2 leaves the plugin required and removes the setting in dorion, because with this on the dorion setting is useless

**Comment by SpikeHD** [comment]
Oh yea this is a legacy thing from waaaaaay before Dorion used Vencord as a frontend-backend, it'll be gone in the next release
