### ISSUE TITLE
[Bug] Buttons on messages from bots doesnt work

### ISSUE THREAD

**Issue by osp54** [SpikeHD/Dorion#114]
**Describe the bug**
Buttons on messages from bots doesnt work.

**To Reproduce**
Click the button

**Expected behavior**
Bot response
**Screenshots**
when clicking button:
![image](https://github.com/SpikeHD/Dorion/assets/76648940/73714ff3-3370-4e93-90aa-9f5d38e7f6f5)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: v1.2.0
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Known issue, see #50
