### ISSUE TITLE
[Feature Request] Flatpak Support

### ISSUE THREAD

**Issue by faan11** [SpikeHD/Dorion#116]
**Is your feature request related to a problem? Please describe.**
Hi.
Thank you for this application. I appreciate it and is useful to me. I wonder if it is in your plan to include this app  in Flathub repo.

**Describe the solution you'd like**
Create flatpak package and maintain in the flathub repo. 

**Describe alternatives you've considered**
We could consider snap but Flatpak is more tailored for desktop application in my opinion. 

**Additional context**

**Comment by SpikeHD** [comment]
Maybe when the [Tauri feature](https://github.com/tauri-apps/tauri/issues/3619) is done, but not until then. Consider using the .AppImage built in [GitHub actions](https://github.com/SpikeHD/Dorion/actions), unless those are still not working, lol
