### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#121]
**Is your feature request related to a problem? Please describe.**
Might be just me being blind, but when I took a look into ``%USERPROFILE%\AppData\Roaming\dorion\config.json`` block_telemetry was set to false.
In the vencord plugins section the required no track plugin was enabled though.
Tho from some older screenshots I could see a switch to block telemetry somewhere in Dorion settings, but I couldn't find it in the most recent version.
I just manually set the value in the config to true, but am I missing something there?

**Describe the solution you'd like**
The switch back or of it's something thats always enabled anyway and the value in the config is just an old remnant, maybe instead of a Switch add a little note in Doriun settings that says that telemetry is blocked by default.

**Comment by cozykitten** [comment]
also forgot a title, sorry

**Comment by SpikeHD** [comment]
Its a legacy feature, thats done by Vencord now
