### ISSUE TITLE
[Feature Request] Support for custom notification sounds

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#122]
...or support for BD plugins since BD has one that does that.
Though that plugin encodes the full notification sounds as base64 string, probably not ideal performance wise?

**Describe the solution you'd like**
Support for custom notification sounds in Dorion itself would be amazing.
Perhaps the alternative discord notification sounds could somehow be unlocked so they wouldnt have to be added as custom sounds?

**Describe alternatives you've considered**
Supporting BD plugins would allow the use of the custom notification sounds plugin.

**Additional context**
For reference
![image](https://github.com/SpikeHD/Dorion/assets/116394977/45269e88-b0a0-4973-b610-983214680aec)
![image](https://github.com/SpikeHD/Dorion/assets/116394977/454d96b6-0319-4036-b903-578ac686fc7e)

**Comment by SpikeHD** [comment]
Currently being worked on [here](https://github.com/Vendicated/Vencord/pull/1765), and will support both links and local sound files.

> Though that plugin encodes the full notification sounds as base64 string, probably not ideal performance wise?

Going off of memory I believe they are cached by the browser in the same way as remote resources so it shouldn't be an issue other than them taking up slightly more disk space.

**Comment by SpikeHD** [comment]
I'm gonna close this since I can't find a good way to do it with Shelter, and since Vencord will have the plugin eventually (and Vencord is still supported in Dorion), it'll be out of my direct control anyways.
