### ISSUE TITLE
[Feature Request] Add Dorion to winget/chocolatey/scoop

### ISSUE THREAD

**Issue by anxshi** [SpikeHD/Dorion#124]
I wish I would be ablte to download Dorion through a package manager :)

**Comment by SpikeHD** [comment]
If you want to use Scoop, there are already [scoop buckets](https://github.com/anderlli0053/DEV-tools) (or [this](https://github.com/okibcn/ScoopMaster), or [this](https://github.com/Small-Ku/turbo-bucket)) that include Dorion. I don't see myself finding the time to figure out how to set up winget or chocolately stuff myself anytime soon, but if someone else would like to help I am open to it!

**Comment by Small-Ku** [comment]
BTW, first two just copying mine (third one). And I don't know why they won't updating it.
Somehow, my installer script works but it is a mess. I may improve it time by time.

**Comment by aliesbelik** [comment]
ScoopInstaller/Extras#13603
