### ISSUE TITLE
[Bug] White Screen issue

### ISSUE THREAD

**Issue by Mystery24601** [SpikeHD/Dorion#125]
**Describe the bug**
The window of Dorion is entirely white on tiny11 startup. refreshing Dorion only shows a split second of the loading screen.

**To Reproduce**
1. Have Dorion and a few plugins (and Tiny11 as well, just to be safe)
2. Start Dorion up (or download plugins that most likely cause the issue)
3. Look at the window (or restart if you have downloaded plugins and then look at the window)

**Expected behavior**
Not a white screen. Just regular Dorion booting up like intended.

**Screenshots**
![White Screen](https://github.com/SpikeHD/Dorion/assets/111801929/0e0c9575-f39a-443f-b373-02b7885824eb)
![Inspect Element Console](https://github.com/SpikeHD/Dorion/assets/111801929/4da34b8f-149a-4e93-911e-67417fb5a965)

**System Info (please complete the following information):**
 - OS: Tiny11
 - Version: 10.0.22621 Build 22621
 - Any other relevant info: Tiny11 is against Microsoft's terms and services but I honestly don't give a crap since I'd rather have a clean and well performing OS than a bloatware hellfire.

**Additional context**
I was getting ready to start the Tiny11 OS and to my surprise, Dorion didn't start up properly and made this issue. It's most likely either caused by plugins, new Dorion updates or Tiny11. but I doubt it's Tiny11 since it worked fine the previous time.

**Comment by Mystery24601** [comment]
btw, I had this issue before, and that was caused by plugins. so I'm thinking that it's a plugin issue.

**Comment by tzrtvevo** [comment]
Same on Win 10. Just re-downloaded 1.3.0 portable, got same result.
No themes. No plugins. No profiles even.

![image](https://github.com/SpikeHD/Dorion/assets/140440984/241b9eaf-000a-4a81-98fb-ed9ef3dc8a49)


**System Info (please complete the following information):**

- OS: Windows 10
- Version: 21H2 19044.1826

**Comment by Mystery24601** [comment]
Good to know.

**Comment by JerukPurut404** [comment]
Same here

**Comment by cozykitten** [comment]
discord threw a major f u our way, vanilla discord even with client mods works™ but plugins are broken and they changed a bunch of classnames so themes are also broken
oh and seems like vanilla discord doesnt like ppl poking around in dev toold so it decided to just crash whenever you open them lol

**Comment by Mystery24601** [comment]
> discord threw a major f u our way, vanilla discord even with client mods works™ but plugins are broken and they changed a bunch of classnames so themes are also broken oh and seems like vanilla discord doesnt like ppl poking around in dev tools so it decided to just crash whenever you open them lol

But hey, that's Discord. Discord doesn't care about their employees, their community and even to the point that they are still incredibly greedy.

**Comment by Small-Ku** [comment]
This seems caused by Vencord, so and also Vencordorion. There is some quote from Vencord server:

> They now pushed this update to stable.
> All themes are broken (theme devs need to fix them)
> A lot of plugins are broken
> Please be patient, while we fix it. We'll start working on it tomorrow, but it might take a few days considering a looot of stuff has broken
> if you're running into issues or crashes, i recommend just uninstalling vencord for now, until we fixed the rest 


> and no, this is not discord trying to kill mods. please do not spread misinformation.
> they heavily changed their build configuration, which makes their output code a lot more clean and modern, which should also improve performance. this is a good update, both for them and for us. it's only a temporary setback.

**Comment by SpikeHD** [comment]
Temporary fix for everyone since the autoupdater can't load if Vencord can't 🤪 :
1. Download the two files here: https://github.com/SpikeHD/Vencordorion/releases/tag/v1.0.22
2. Put them in `%APPDATA%\dorion\injection` on Windows, `~/Library/Application Support/dorion/injection` on MacOS, and `$XDG_CONFIG/dorion/injection` on Linux (I think).

Dorion will probably prompt you to update stuff, which will just download the same files you just put there, so it's safe to say "Yes" to the prompt.

I've already begun working on a plugin(s) for Shelter that does most of the Vencord stuff, so things like this happen less frequently. If it works well enough/identically to the custom stuff in Vencordorion, I'll probably switch to Shelter entirely (but still support Vencord as an additional, optional mod of course!) 

There will also be a release of Dorion later today using this new Vencordorion build so people don't have to dig through their files like cavemen.

**Comment by SpikeHD** [comment]
Also for future reference, you can load Dorion with the `--safemode` (eg. `.\Dorion.exe --safemode`) flag if something like this happens and there is no immediate solution

**Comment by SpikeHD** [comment]
Oh, one more alternative: I just reran the build job for the latest commit, so if you hate your file browser or something, you should be able to download a build for your platform here: https://github.com/SpikeHD/Dorion/actions/runs/6602059291. As a bonus, you'll be on a more updated Dorion than the people who just download releases :P

**Comment by piotr25691** [comment]
> Oh, one more alternative: I just reran the build job for the latest commit, so if you hate your file browser or something, you should be able to download a build for your platform here: [SpikeHD/Dorion/actions/runs/6602059291](https://github.com/SpikeHD/Dorion/actions/runs/6602059291). As a bonus, you'll be on a more updated Dorion than the people who just download releases :P

Thank you for the fix, now I can properly try out Dorion (I'm moving from Discord's official client to this now)

**Comment by SpikeHD** [comment]
> (I'm moving from Discord's official client to this now)

one of us, one of us

**Comment by piotr25691** [comment]
> > (I'm moving from Discord's official client to this now)
> 
> one of us, one of us

Hell yeah, by the way Vencord is on the fixing spree and a bunch of plugins were fixed

**Comment by SpikeHD** [comment]
Yea I know, I'm gonna let them kinda do their thing and merge it all in later

**Comment by SpikeHD** [comment]
Solved in the newest release, future Vencord updates will be slowly added as they are done, so keep update notifications on in Dorion to stay up-to-date!

**Comment by piotr25691** [comment]
> Solved in the [newest release](https://github.com/SpikeHD/Dorion/releases/tag/v1.4.0), future Vencord updates will be slowly added as they are done, so keep update notifications on in Dorion to stay up-to-date!

almost there in the fixing, there have been 4 more minor fix commits on Vencord, you might want to pull those in

**Comment by cozykitten** [comment]
man I love how my secret magic trick just works every time.
It's called "go to sleep and things magically work when I wake up again"

**Comment by jacksongoode** [comment]
Still experiencing this on 2.0

**Comment by SpikeHD** [comment]
> Still experiencing this on 2.0

Make a new issue please! And include devtools console output
