### ISSUE TITLE
[Bug] Show Hidden Channels displays wrongly

### ISSUE THREAD

**Issue by Banaanae** [SpikeHD/Dorion#126]
**Describe the bug**
Locks display black (rather than the discord grey text)
Clicking on channels displays large lock

**To Reproduce**
1.  Turn on SHC and restart
2. Observe lock colour on a hidden channel
3. Click and see large lock

**Expected behavior**
Lock is discord grey
Shows information about the channel

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/83927639/a3e5ada5-0694-4755-8175-fe006eee4429)
![image](https://github.com/SpikeHD/Dorion/assets/83927639/8c949c88-135b-41d3-bcd0-530022d059d1)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.4.0

**Additional context**
This might be a vencord issue, sorry if so

**Comment by piotr25691** [comment]
> **Describe the bug** Locks display black (rather than the discord grey text) Clicking on channels displays large lock
> 
> **To Reproduce**
> 
>     1. Turn on SHC and restart
> 
>     2. Observe lock colour on a hidden channel
> 
>     3. Click and see large lock
> 
> 
> **Expected behavior** Lock is discord grey Shows information about the channel
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/83927639/278284722-a3e5ada5-0694-4755-8175-fe006eee4429.png) ![image](https://user-images.githubusercontent.com/83927639/278284818-8c949c88-135b-41d3-bcd0-530022d059d1.png)
> 
> **System Info (please complete the following information):**
> 
>     * OS: Windows 11
> 
>     * Version: v1.4.0
> 
> 
> **Additional context** This might be a vencord issue, sorry if so

Yep, it most likely is. Vencord is still partially broken. Ven has yet to conclude his fixing for Vencord to work, consequently also Dorion's Vencord fork.

**Comment by SpikeHD** [comment]
Vencord is still brokey, you’ll just have to wait

**Comment by piotr25691** [comment]
> Vencord is still brokey, you’ll just have to wait

Thanks for explaining the issue.
