### ISSUE TITLE
[Bug] no audio when screen sharing selective apps instead of full screen

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#128]
**Describe the bug**
When screen sharing and selecting one window instead of the entire screen the audio of the window is not transmitted.

**To Reproduce**
Steps to reproduce the behavior: Share window with audio and ask a friend.

**Expected behavior**
Audio should be transmitted

**System Info (please complete the following information):**
 - OS: Win 11 22H2
 - Version: 1.4.0 and before
 - Any other relevant info: don't think so?

**Additional context**
Idk if that's a limitation of web discord or if that's actually fixable tho.

**Comment by SpikeHD** [comment]
I believe this is entirely a limitation of WebView2. If it updates to support this, Dorion will automatically support it as well. you probably [want to screenshare in fullscreen](https://github.com/SpikeHD/Dorion/issues/153) anyways, lol
