### ISSUE TITLE
[Bug] Dorion doesn't work correctly after update to 1.4.0

### ISSUE THREAD

**Issue by electricsteve** [SpikeHD/Dorion#129]
**Describe the bug**
I updated to 1.4.0 and it just went broken, it opens with theme, icons and stuff, but nothing from my account and i can't access settings.

**To Reproduce**
1. install 1.3.0
2. update to 1.4.0
Boom, don't know if it is reproducable, it just happened.

**Expected behavior**
Just work.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/96793824/1a91b96d-f378-4104-9a87-03cdf6da0e13)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: from 1.3.0 to 1.4.0
 - Any other relevant info: IDK

**Additional context**
IDK

**Comment by SpikeHD** [comment]
Try launching Dorion from the terminal using the "--disable-plugins" flag. Discord updated like two days ago, causing client mods to break pretty bad, and this may just be a remnant of that. Once they're disabled, just manually enable them again one by one. Feel free to also post the output from the devtools console if that doesn't work.

**Comment by SpikeHD** [comment]
You can try doing the same solution [I mention here](https://github.com/SpikeHD/Dorion/issues/125#issuecomment-1779479249), but instead of downloading the release I linked, download [this one](https://github.com/SpikeHD/Vencordorion/releases/tag/v1.0.26). Let me know if that works

**Comment by JerukPurut404** [comment]
Still can't open it

**Comment by electricsteve** [comment]
> You can try doing the same solution [I mention here](https://github.com/SpikeHD/Dorion/issues/125#issuecomment-1779479249), but instead of downloading the release I linked, download [this one](https://github.com/SpikeHD/Vencordorion/releases/tag/v1.0.26). Let me know if that works

This worked for me!

**Comment by SpikeHD** [comment]
@JerukPurut404 Download whatever is latest [here](https://github.com/SpikeHD/Vencordorion/releases) and do the same thing. It should definitely work unless you are putting things in the wrong spot. If it still doesn't work please open a new issue.
