### ISSUE TITLE
[Feature Request] discord rpc

### ISSUE THREAD

**Issue by toprak** [SpikeHD/Dorion#13]
you can use https://github.com/OpenAsar/arrpc it could make it easy to implement

**Comment by SpikeHD** [comment]
This is a good starting point, ideally I want to avoid requiring the user to install NodeJS and do the whole setup BUT I could most likely create a Rust-based binary/library that I can then shove into this.

Great starting point, thank you!

**Comment by SpikeHD** [comment]
Just an update, this is on my radar as something to do now that v0.6.0 is released

**Comment by SpikeHD** [comment]
Currently working on the RPC lib/binary, which will be public once it actually is able to do something. Hopefully you can expect this to be integrated into Dorion pretty soon

**Comment by SpikeHD** [comment]
Getting there! https://www.github.com/SpikeHD/rsRPC
![image](https://github.com/SpikeHD/Dorion/assets/25207995/7f263490-b53d-4bce-98df-c1665ac23134)

**Comment by toprak** [comment]
lets gooooooooooo

**Comment by SpikeHD** [comment]
It's been an honor having this as the longest standing issue for more than half a year, but it is time it finally comes to a close. As of 90d1b7baed87ddd797c04a9cd07c865d12fcd5f9, this is now implemented (not perfectly, but it will be expanded in the future).

o7

**Comment by toprak** [comment]
@SpikeHD that's really good job! thanks!
