### ISSUE TITLE
[Bug] Themes still broken

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#134]
**Describe the bug**
Using material theme from CapnKitten, theme is still broken even tho the theme itself is fixed.
Might be because Dorion may be loading themes before discord's main css or something like that?
The same issue was on BD as well before they updated, this is what CapnKitten said in announcements:

> BD users will encounter obvious areas that are not styled. As it currently stands, BD loads themes before Discord's main css file, so a lot of things get overwritten by Discord's code. BD might address this in a later update, but if not, I will adapt the themes to this change. For the time being, you'll have to deal with this or switch over to another client mod.

**To Reproduce**
Load any theme but in my testing Translucence and Material from CapnKitten

**Expected behavior**
Since the themes are fixed for discords recent class changes they should style normally.

**System Info (please complete the following information):**
 - OS: win11
 - Version: 2.0.0

**Comment by SpikeHD** [comment]
That's odd, I thought Dorion was loading them pretty late but I'll do some experimentation

**Comment by SpikeHD** [comment]
Fixed it by appending styles to the document body instead of the <head>, lol
0b1d202
