### ISSUE TITLE
[Bug] Autorun denie

### ISSUE THREAD

**Issue by hitman72ita** [SpikeHD/Dorion#135]
**Describe the bug**
If at the first start I denie the registry modifying to add the program in the startup list with antivirus, the program quits

**Expected behavior**
I don't wont that this program will run automatically during the startup process/modify registry

**System Info (please complete the following information):**
 - OS: Windows 10

**Comment by SpikeHD** [comment]
I *think* this is fixed in 3ea1353, feel free to test a build action from the commit or just wait for the next release 👍

**Comment by hitman72ita** [comment]
ok, with the latest update it works. thank you a lot
