### ISSUE TITLE
[Bug] Dorion settings don't always show up

### ISSUE THREAD

**Issue by piotr25691** [SpikeHD/Dorion#138]
**Describe the bug**
Dorion's settings don't always show up and need a refresh to properly appear.

**To Reproduce**

1. Install Dorion (v2.1.0, or the current build artifact)
2. Open it up
3. Go to settings
4. See that the Dorion settings aren't there

**Expected behavior**
Describe what should be expected here.

Dorion settings should've appeared without refreshing the client.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.1.0
 - Any other relevant info: None

**Additional context**

No other context available.

**Comment by Friedlimbs** [comment]
I'm having the exact same problem! Same OS, too.

**Comment by SpikeHD** [comment]
I believe this should be fixed as of f0d6732, feel free to test a build action once they complete and reopen if it still happens

**Comment by Friedlimbs** [comment]
How do I fix it, because I don't understand what you mean, I'm sorry.

> I believe this should be fixed as of [f0d6732](https://github.com/SpikeHD/Dorion/commit/f0d6732acd3a961d17507a9ccf715debdfcba926), feel free to test a build action once they complete and reopen if it still happens

**Comment by SpikeHD** [comment]
@Friedlimbs If you ever want to test a new fix or just be on the cutting-edge, you can take a look at [GitHub actions](https://github.com/SpikeHD/Dorion/actions/workflows/build.yml), which is where automated builds go. You can either find a build for a specific commit (like the one linked in my previous comment), or just download the most recent one once it has succeeded by clicking it and scrolling down to the bottom. They usually take about 18 minutes.
