### ISSUE TITLE
[Bug] Reloading Discord issue

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#139]
**Describe the bug**
Occationally when doing CTRL + R, it will reload Discord without any of the dorion features. Same as in earlier versions where you were able to browse the web inside Dorion. It just loads normal discord website.

**To Reproduce**
Press CTRL + R a bunch of times ig?

**Expected behavior**
Dorion reloads as normally

**Screenshots**
![Screenshot 2023-11-02 170002](https://github.com/SpikeHD/Dorion/assets/91745601/18607f1f-d1a0-45fe-9454-df53f7a1a7c9)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.1.0
 - Any other relevant info: I never experienced this in earlier versions

**Comment by cozykitten** [comment]
same thing when just quitting and relaunching for me:
fresh install and clearing data and it all works normally when I start it the first time.

Then I set my audio input device, enable "minimize to tray" in dorion settings, quit dorion, restart dorion -> no dorion settings, only shelter
![image](https://github.com/SpikeHD/Dorion/assets/116394977/29ceae0b-e79d-4664-b02c-b0b029a030f6)

When I go to shelter settings and disable some of the plugins the switch turns off, it doesn't turn on again no matter how much I click on it. after restarting dorion all the default switches are on again (so all aside inline CSS and shelter RPC) and dorion settings are still missing.
(btw what does shelterRPC do?)

**Comment by Temanor** [comment]
> (btw what does shelterRPC do?)

Rich presence plugin ported to Shelter. Allows game detection for Dorion.

**Comment by SpikeHD** [comment]
@cozykitten I believe your issue is slightly different, and was described in #138. If you'd like you can try a build artifact from [GitHub Actions](https://github.com/SpikeHD/Dorion/actions/runs/6740853180)

**Comment by SpikeHD** [comment]
@Temanor let me know if v2.2 fixed this 👍

**Comment by SpikeHD** [comment]
Is this still happening on v3?

**Comment by Temanor** [comment]
![example](https://github.com/SpikeHD/Dorion/assets/91745601/cc91afd4-afd4-469d-a1e2-95df582d151b)
Yes it does

**Comment by Temanor** [comment]
No. It seems to be fixed now. I have tried 30-40 times now, and can't get it to happen.

**Comment by Temanor** [comment]
I did manage to get a white screen by spamming Ctrl+R a couple of times though.

**Comment by SpikeHD** [comment]
Do you ave any additional plugins enabled (eg Vencord?). Could be that its loading too soon/too late, feel free to make a new issue if you figure out whats causing it.
