### ISSUE TITLE
Dorion Settings disappeared

### ISSUE THREAD

**Issue by Small-Ku** [SpikeHD/Dorion#14]
When language of Discord is set as non-English languages, Dorion Settings can not be accessed.
![Example with Traditional Chinese](https://user-images.githubusercontent.com/16464896/211217083-44285027-1093-4d4e-8ddb-af77651457e6.png)
![Example with Japanese](https://user-images.githubusercontent.com/16464896/211217096-bc7efe18-c904-40fd-8ce8-0ec877b62b12.png)

https://github.com/SpikeHD/Dorion/blob/main/src-tauri/injection/injection.js#L89
Seems like `aria-label` change with the language. For example, it is `aria-label="使用者設定"` with Traditional Chinese.
It seems that "Friend Requests", "Nitro", and "HypeSquad" are not localized with languages currently.

**Comment by SpikeHD** [comment]
Fixed in recent commit, will be made into a release soon!
