### ISSUE TITLE
[Bug] Themes not working

### ISSUE THREAD

**Issue by polysymphonic** [SpikeHD/Dorion#142]
**Describe the bug**
Regular themes (in /themes) and vencord themes (including online/linked themes) not working at all.

**To Reproduce**
Add any theme.

**Expected behavior**
Themes working.

**Screenshots**
![explorer_lSBtvJMgZt](https://github.com/SpikeHD/Dorion/assets/147699598/eff6eb59-98f8-424e-9b1f-b7f1ffbb3d54)
![Dorion_l4KtQrjXtl](https://github.com/SpikeHD/Dorion/assets/147699598/cd6094e7-2643-46cd-931f-f4b9f8792acf)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: 2.1.0
 
**Additional Context:**
I have tried naming the file ".theme.css" and ".css", and restarting. None worked.

**Comment by SpikeHD** [comment]
Very odd, I just tried amoled-cord and it worked just fine for me. Do you mind posting devtools output (Ctrl+Shift+i -> "Console" tab)?

**Comment by SpikeHD** [comment]
Oh, also might help to clear CSS cache in "Performance & Extras"

**Comment by piotr25691** [comment]
> **Describe the bug** Regular themes (in /themes) and vencord themes (including online/linked themes) not working at all.
> 
> **To Reproduce** Add any theme.
> 
> **Expected behavior** Themes working.
> 
> **Screenshots** ![explorer_lSBtvJMgZt](https://user-images.githubusercontent.com/147699598/280166855-eff6eb59-98f8-424e-9b1f-b7f1ffbb3d54.png) ![Dorion_l4KtQrjXtl](https://user-images.githubusercontent.com/147699598/280166859-cd6094e7-2643-46cd-931f-f4b9f8792acf.png)
> 
> **System Info (please complete the following information):**
> 
> * OS: Windows 10
> * Version: 2.1.0
> 
> **Additional Context:** I have tried naming the file ".theme.css" and ".css", and restarting. None worked.

Mind I tell you, you forgot to load in Vencord’s CSS. Load that too to fix some of your problems

**Comment by SpikeHD** [comment]
While I don't know why amoled-cord didn't work for you, I caught an edge-case in ComfyGrey that would cause it to not apply. This has been fixed in 54ff34b, and you can either wait for the next release, or download a build from [GitHub Actions](https://github.com/SpikeHD/Dorion/actions/runs/6749247554) to test.
