### ISSUE TITLE
[Bug] Dorion settings gone when reloading

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#143]
**Describe the bug**
Dorion setting section is only there the first time when starting dorion after a fresh install.
After closing and restarting it after that it's missing and only comes back after reinstalling and removing app data.

**To Reproduce**
Install, launch, do stuff, quit, re-launch.

**System Info (please complete the following information):**
 - OS: [e.g. Windows 11 22H2
 - Version: 2.1 (also was on 2.0)

**Additional context**
I downloaded the newest commit from Actions and put that in dorions installation folder but that didn't fix it.

**Comment by SpikeHD** [comment]
Hmm, maybe try this:

1. Open Dorion
2. Run this:
```js
Object.keys(shelter.plugins.installedPlugins()).forEach(p => shelter.plugins.removePlugin(p))
```
3. Close Dorion
4. Install again via `.msi` (recommended) or however you prefer
5. Open Dorion

Ideally this should fix it, it's possible the plugins are just in a borked state or something and need a full refresh

**Comment by piotr25691** [comment]
> Hmm, maybe try this:
> 
>     1. Open Dorion
> 
>     2. Run this:
> 
> 
> ```js
> Object.keys(shelter.plugins.installedPlugins()).forEach(p => shelter.plugins.removePlugin(p))
> ```
> 
>     3. Close Dorion
> 
>     4. Install again via `.msi` (recommended) or however you prefer
> 
>     5. Open Dorion
> 
> 
> Ideally this should fix it, it's possible the plugins are just in a borked state or something and need a full refresh

For me that didn't work and behavior of those plugins are repeating #138 again, I don't think it got properly fixed yet.

**Comment by cozykitten** [comment]
of course things magically work now when I make an issue about it....
so well, if it happens again ill try what u mentioned above.

**Comment by SpikeHD** [comment]
I've made plugin stuff more reliable recently, so if anyone is having consistent issues with them, they should [try an Actions build](https://github.com/SpikeHD/Dorion/actions/runs/6779974242). If it's not working, try deleting the "shelter" indexedDB like so, and then refreshing:

![image](https://github.com/SpikeHD/Dorion/assets/25207995/d3386fa2-a717-43c0-b20b-7f807b1c4c41)

Would appreciate if people are able to report back, since I'm itching to make a new release :)

**Comment by piotr25691** [comment]
> I've made plugin stuff more reliable recently, so if anyone is having consistent issues with them, they should [try an Actions build](https://github.com/SpikeHD/Dorion/actions/runs/6779974242). If it's not working, try deleting the "shelter" indexedDB through DevTools like so, and then refreshing:
> 
> ![image](https://user-images.githubusercontent.com/25207995/280919980-d3386fa2-a717-43c0-b20b-7f807b1c4c41.png)
> 
> Would appreciate if people are able to report back, since I'm itching to make a new release :)

Have updated to that build, still needed one refresh to load plugins or else #138 would repeat

**Comment by piotr25691** [comment]
> Has it appeared again since the single refresh? Or has it been stable after that?

Yes it appeared again I refreshed. It also caused any custom CSS to not apply because the CSS editor was not loaded

**Comment by cozykitten** [comment]
For me the issue disappeared from one day to the next, I updated to a more recent actions build and it would still disappear settings and bug plugins but the next day all was working fine.

Only weird thing now is when I exit dorion it shows a little popup "do you wanna leave this website?"

**Comment by trinkey** [comment]
I've been getting an issue similar to this where every time i launch or reload the client I'm forced to re-login again. This happened both on the old Vencord version (v1.4.0) and the new Shelter version (v2.1.0). (Windows 11 latest ver.)

**Comment by SpikeHD** [comment]
Sounds a lot like #100 which didn’t end up having a solution. If you figure it out though feel free to let me know

**Comment by SpikeHD** [comment]
> Only weird thing now is when I exit dorion it shows a little popup "do you wanna leave this website?"

Sounds like you’re on an old build @cozykitten I got rid of that days ago 😄

**Comment by cozykitten** [comment]
all working for me on 2.2
