### ISSUE TITLE
[Bug] Presence not working

### ISSUE THREAD

**Issue by Mason-17** [SpikeHD/Dorion#144]
**Describe the bug**
Rich presence via the built-in plugin (shelter and aRPC) doesn't show anything as status, even after a full restart and re-install.

**To Reproduce**
1. use dorion
2. don't get status

**Expected behavior**
Status should appear on the bottom.

**Screenshots**
![Screenshot 2023-11-06 144344](https://github.com/SpikeHD/Dorion/assets/122631948/bac871dc-0a18-4c71-a704-3ad970c47c8f)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.1.0
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Do they show messages showing they have properly connected to the RPC server? What games/programs are you testing? It's worked for me in basic games (TBoI, Dead Cells), and using an Actions build allows for advanced RPC like the VSCode extension to also work fine on my end.

**Comment by Mason-17** [comment]
> Do they show messages showing they have properly connected to the RPC server? What games/programs are you testing? It's worked for me in basic games (TBoI, Dead Cells), and using an Actions build allows for advanced RPC like the VSCode extension to also work fine on my end.

Sometimes it does, sometimes it says it didn't connect, and sometimes it doesn't say anything at all.

**Comment by SpikeHD** [comment]
Not saying anything is likely a symptom of #143 where plugins seem to just... not load sometimes. Also, some games do not use the basic process detection, only a fancier one, which is available in Actions builds if you'd like to test that. Actions builds should also be more stable in terms of plugins working, so I recommend you give those a test.

(Also rsRPC, my arRPC recreation, can sometimes take a minute to detect a game. If you own one of the games I mentioned above I suggest you use those to test that it is working properly)

**Comment by Mason-17** [comment]
> Not saying anything is likely a symptom of #143 where plugins seem to just... not load sometimes. Also, some games do not use the basic process detection, only a fancier one, which is available in Actions builds if you'd like to test that. Actions builds should also be more stable in terms of plugins working, so I recommend you give those a test.
> 
> (Also rsRPC, my arRPC recreation, can sometimes take a minute to detect a game. If you own one of the games I mentioned above I suggest you use those to test that it is working properly)

Well i downloaded the one from Actions and it is consistently picking up games now, its just slow. It also doesn't seem to update regularly (for music apps such as MusicBee)

**Comment by SpikeHD** [comment]
I've made updates to rsRPC that should make it both faster and ideally more stable. Feel free to try another more recent actions release and report back 👍

**Comment by Mason-17** [comment]
> I've made updates to rsRPC that should make it both faster and ideally more stable. Feel free to try another more recent actions release and report back 👍

will do

**Comment by SpikeHD** [comment]
This should be fixed in v2.2
