### ISSUE TITLE
[Bug] Desktop notifications not showing user icon

### ISSUE THREAD

**Issue by Mason-17** [SpikeHD/Dorion#145]
**Describe the bug**
There are no notifications (despite them being on). Discord status is also set to active. There is also no change in the icon on the bottom of the screen.

**To Reproduce**
1. use Dorion
2. get notification
3. only hear sound, but don't get actual notification

**Expected behavior**
Desktop notifications and icon change.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.1.0
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
I think(?) this is a symptom of plugins not properly starting (#143), unless you know for sure things like Dorion Settings were showing during the session you noticed notifications show up. Next time you notice them not showing up, check DevTools. You might have something along the lines of a "permission denied" error which I believe you can fix by clearing web data (middle button in Performance & Extras)

**Comment by Mason-17** [comment]
> I think(?) this is a symptom of plugins not properly starting (#143), unless you know for sure things like Dorion Settings were showing during the session you noticed notifications show up. Next time you notice them not showing up, check DevTools. You might have something along the lines of a "permission denied" error which I believe you can fix by clearing web data (middle button in Performance & Extras)

Thing is though, the notifications haven't worked. I haven't used Dorion for about a month, but I remember notifications working then.

**Comment by SpikeHD** [comment]
Back then I was using a Vencord patch, but since I've nixed Vencord in favor of Shelter, that patch has been replaced with slightly different functionality. I'll just move the notifications to the backend fully since that should also fix a problem someone was having with Windows 7

**Comment by Mason-17** [comment]
> Back then I was using a Vencord patch, but since I've nixed Vencord in favor of Shelter, that patch has been replaced with slightly different functionality. I'll just move the notifications to the backend fully since that should also fix a problem someone was having with Windows 7

Awesome, can't wait to see it!

**Comment by SpikeHD** [comment]
I've moved notifications to be (almost) entirely handled by the backend, so no more permission screwery. Combined with the more stable plugins stuff, this issue should be fixed when the next release hits, feel free to reopen if it doesn't fix it

**Comment by Mason-17** [comment]
Reopening, since the taskbar icon doesn't show a message as incoming. However, there is now a desktop notification when that setting is enabled. Also, no pfp icons are in the desktop notification.

**Comment by SpikeHD** [comment]
Taskbar icon is a separate issue (#27) already, but the missing icon should be something I can solve

**Comment by Mason-17** [comment]
> Taskbar icon is a separate issue (#27) already, but the missing icon should be something I can solve

Didn't realize it was already an issue. Thanks.

**Comment by SpikeHD** [comment]
This has been added as of 4cf1885b89f59e5716a2ed826125a9c96ce23b10, and will be available in the next release!

This breaks on Windows 7, so future releases will no longer show system notifications on that platform. While this is unfortunate, I couldn't think of an easy way of keeping both notification systems in, and since Windows 7 is EOL, Windows 10/11 UX gets priority.

![image](https://github.com/user-attachments/assets/91973c6f-c6d2-45a1-b284-7f48f213039b)
(excuse the Powershell icon, lol)
