### ISSUE TITLE
[Feature Request] Arch Linux support.

### ISSUE THREAD

**Issue by LhymeFruit** [SpikeHD/Dorion#146]
**Is your feature request related to a problem? Please describe.**
The linux builds of Dorian only supports debian.
**Describe the solution you'd like**
arch linux support for dorian
**Describe alternatives you've considered**

**Additional context**

**Comment by SpikeHD** [comment]
Dorion is already [on the AUR](https://aur.archlinux.org/packages/dorion-bin) (not maintained by me)
