### ISSUE TITLE
[Question] Can I use portable zip version to update instead of installer?

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#149]
Can I just overwrite Dorion.exe, Updater.exe, injection/ and icons/ with the ones from the portable zip when a new version gets released or do I have to run the installer that prompts me to uninstall and reinstall every time?

**Comment by piotr25691** [comment]
> Can I just overwrite Dorion.exe, Updater.exe, injection/ and icons/ with the ones from the portable zip when a new version gets released or do I have to run the installer that prompts me to uninstall and reinstall every time?

Why is that a problem? It's not like you lose your settings when you update Dorion using the installer

**Comment by SpikeHD** [comment]
Yes you can just overwrite the files if you’d prefer. The only thing Dorion uses to tell if its portable or not is whether “config.json” is in the same dir as the exe, so it won’t do anything funky.
