### ISSUE TITLE
[Bug] window save positions does not work at all..

### ISSUE THREAD

**Issue by haxerman123** [SpikeHD/Dorion#151]
whenever i changed my window size of dorion, and then restart the client it always starts in a small window (like 800x600) and moves to the side of my screen.

**Comment by piotr25691** [comment]
yeah same, I would like the window size to be kept at what I set it to be

**Comment by SpikeHD** [comment]
@haxerman123 Can you please edit your issue to use the [issue template](https://github.com/SpikeHD/Dorion/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D) please? Gives me more/better information :)

**Comment by SpikeHD** [comment]
Actually, no need this time, this should be fixed in 21e0aa9, but next time please use the templates!
