### ISSUE TITLE
[Bug] plugins disabled on shelter don't get disabled after a reload..

### ISSUE THREAD

**Issue by haxerman123** [SpikeHD/Dorion#154]
idk if this is a shelter bug or a dorion client bug but every time i disable a plugin it doesn't save, oddly the inline css plugin does get disabled properly but others don't

**Comment by SpikeHD** [comment]
It depends which you are disabling. Some are enabled by default and reenabled when restarting Dorion (such as Dorion Settings, since it's pretty vital :P)

**Comment by SpikeHD** [comment]
Take a look [at these](https://github.com/SpikeHD/Dorion/blob/a0263e8a9d723d598ce4ab5ff0751ad64306bbb9/src-tauri/injection/injection.js#L165). Any that are marked as "required: true" are plugins that control core Dorion functions and need to be enabled.

**Comment by haxerman123** [comment]
oh ok
