### ISSUE TITLE
[Bug] white screen at startup archlinux (version 2.2.1-2)

### ISSUE THREAD

**Issue by DaRandomCube** [SpikeHD/Dorion#156]
**Describe the bug**
on arch linux, when you install dorion-bin-2.2.1-2 from aur and you lunch it, you will be greeted with a white screen

**To Reproduce**
install dorion using command `yay -S dorion`

**Expected behavior**
dorion lunch normally

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/93283139/716dc19b-5509-4c0b-a01b-9534021dbd73)
thats it

**System Info (please complete the following information):**
 - OS: cachy os linux [arch based] with gnome desktop
 - Version: dorion-bin-2.2.1-2
 - Any other relevant info: i've installed it in the past, reinstalled many distros after that and keeping /home partition to reuse it

**Additional context**

**Comment by SpikeHD** [comment]
This has been (kinda) fixed in fef888ca7f134c144d3493ec92adf424e10fe857 so you will just have to wait until the next release 👍

**Comment by thisisignitedoreo** [comment]
void x86_64 glibc, dorion 2.2.1, awesomewm, same deal.
