### ISSUE TITLE
[Bug] No detected game bg-colour choice

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#157]
**Describe the bug**
Hard to read with certain themes.
In my case, Mocha.

**To Reproduce**
Use a theme, which changes the light gray colour used as background colour when there is no detected games.

**Expected behavior**
Contrast should be bigger, so the text is easier to read.

**Screenshots**
![Screenshot 2023-11-23 123811](https://github.com/SpikeHD/Dorion/assets/91745601/2698c045-db15-4db3-96fc-f5ee292754b8)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.2.1
 - Any other relevant info: Wouldn't necceceraly call it a bug, but something that could be improved upon.

**Comment by SpikeHD** [comment]
This belongs in [SpikeHD/shelter-plugins](https://github.com/SpikeHD/shelter-plugins/), not here
