### ISSUE TITLE
Close button doesn't work [Bug]

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#158]
**Describe the bug**
Clicking the X in the modal for adding new games, doesn't actually do anything.

**To Reproduce**
Go into Registered games in settings
Click "Add a game"
click the "X"

**Expected behavior**
The modal should close

**Screenshots**
![x](https://github.com/SpikeHD/Dorion/assets/91745601/3b268556-a7ab-4c9c-acab-6889849f001d)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.2.1
 - Any other relevant info: esc and clicking anywhere outsite the modal still works.

**Comment by SpikeHD** [comment]
Fixed in 8c56f2ec7cfb00777adbd7447483d4c0dbe18a11
