### ISSUE TITLE
[Bug] Rich Presence's "Add Game" menu doesn't work

### ISSUE THREAD

**Issue by ARandomGuylol** [SpikeHD/Dorion#160]
I was playing Friday Night Funkin: Psych Engine, and i installed Dorion while doing so. But idk why, but my rich presence doesn't work.
And even when trying to add it manually, the "Add Game" menu just displays "Please Wait"
![image](https://github.com/SpikeHD/Dorion/assets/101367788/0975a898-032c-4708-837a-d9b13f13ba26)
and before you ask, yeah, i do have ShelteRPC on.

Forgot to mention that the game has a dedicated RPC setting, which is checkmarked as yes.

**Comment by SpikeHD** [comment]
That is placeholder UI for features that will be available in the next update
