### ISSUE TITLE
[Bug] Dorion version number in settings not showing up

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#164]
**Describe the bug**
The dorion version number in the settings doesn't appear the first time you enter the settings after restarting, but *does* appear the second time.

**To Reproduce**
press Ctrl+R
Enter settings
Scroll down to the bottom of the page

**Expected behavior**
The Dorion version number should appear every time you enter the settings.

**Screenshots**
![Screenshot 2023-12-05 210342](https://github.com/SpikeHD/Dorion/assets/91745601/e1f26f53-9cab-4ac5-b6e1-7ab10c872318)

**System Info:**
 - OS: Windows 11
 - Version: v2.3.0

**Additional context**
This was why I didn't see it when I reloaded 6 times, but appeared right away after I entered the settings to check once more after you sent the screenshot.

**Comment by SpikeHD** [comment]
Is this still happening on v3?

**Comment by Temanor** [comment]
Yes it is.
![example](https://github.com/SpikeHD/Dorion/assets/91745601/dbdd83de-8ff4-48c7-b7eb-9b5df5806d4d)

**Comment by Temanor** [comment]
I tried figuring out what was causing this, and it seems like it is caused by my theme. I have no idea how this makes any sense, but removing it and restarting Dorion will show the version number like intended.
Here is the theme if you would like to test:
[mocha.zip](https://github.com/SpikeHD/Dorion/files/13760379/mocha.zip)

**Comment by Temanor** [comment]
Forgot to mention, I did not test with other themes.

**Comment by SpikeHD** [comment]
I've made changes to how this works, is it still happening? Or is it really just the theme borking it?

(Shelter plugins are now pulled from the internet on the fly so you can just reopen/refresh and the change will apply)

**Comment by Temanor** [comment]
I'm not sure what was happening. Nor do I understand how the theme could be affecting this, but when I set the theme to none, it worked normally.
I'm unable to test now, but will try to remember it tomorrow morning.

**Comment by Temanor** [comment]
Nevermind? I tried again today. Looks like it only happens with Vencord enabled.
I think I might have had Vencord disabled after testing white screen issue mentioned in #139 and thought it was because of the theme.

**Comment by SpikeHD** [comment]
is this still happening?

**Comment by Temanor** [comment]
No. I believe it was fixed when you changed how Vencord was injected, not that long ago.
