### ISSUE TITLE
[Bug] Unable to change icons with CSS

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#165]
**Describe the bug**
I tried to revert the icons to the old ones, but the snippet didn't work.
The snippet I used was [this](https://davart154.github.io/Themes/Icon%20Revert%202023/2023%20Icon%20Revert.css)

**To Reproduce**
Copy paste the css, or import into your theme and restart Dorion.

**Expected behavior**
Icons should be reverted to the old ones.

**Screenshots**
![Screenshot 2023-12-07 112346](https://github.com/SpikeHD/Dorion/assets/91745601/10cd3ca8-72a0-4f04-8202-cd08636a2d1e)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.3.0
 - Any other relevant info: Works in other clients like BD and Vencord

**Comment by luximus-hunter** [comment]
The issue lies within cors errors. Images hosted outside of discord cannot be accessed properly, as visible in the console when trying to load the snippet.

**Comment by SpikeHD** [comment]
Using the inline CSS plugin it will definitely never work, and Dorion has always had (basically) unfixable [issues](https://github.com/SpikeHD/Dorion#known-issues) with CSS image loading from themes.

**Comment by Temanor** [comment]
I didn't know that counted for SVG icons as well

**Comment by SpikeHD** [comment]
Oh actually, it did end up working through inline CSS (not using a URL import, but pasting the contents of the link you sent). Maybe the CSS preprocessor has some weird edge case that breaks... idk, something

Either way keeping this closed since there is at least *a* solution.
