### ISSUE TITLE
[Bug] CSP prevents external images from loading

### ISSUE THREAD

**Issue by piotr25691** [SpikeHD/Dorion#166]
**Describe the bug**
Describe the problem here.

Dorion's CSP (Content Security Policy) prevents external images from loading.
This breaks some themes, and also some plugins like Vencord's `Decor` plugin.

**To Reproduce**

1. Try to use a theme / plugin which loads an image that was not hosted on Discord.
2. See it not loading correctly.

**Expected behavior**
Describe what should be expected here.

The image should load correctly.

**Screenshots**

![image](https://github.com/SpikeHD/Dorion/assets/71488561/1b145cea-d075-4c3f-94a6-55b0f87fb37c)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v2.3.0
 - Any other relevant info: IDK

**Additional context**

Is this fixable? I think like you could probably try to bypass CSP in Dorion, right?

**Comment by SpikeHD** [comment]
This is known and only fixable if Tauri ever supports rewriting request headers as they come in. As it stands, [it is not possible on all platforms](https://github.com/tauri-apps/tauri/discussions/6187#discussioncomment-4881352) and therefore is not possible in Dorion in any capacity until this changes.
