### ISSUE TITLE
[Bug] Full-screen during screenshare/video/voice channel screen does not full-screen the window

### ISSUE THREAD

**Issue by plutonium-239** [SpikeHD/Dorion#171]
**Describe the bug**
When on a video/screenshare/voice channel screen ( [this screen](https://support.discord.com/hc/article_attachments/4419649713175/text-chat-in-voice-message-bubble-icon-demo-desktop-browser.gif), pressing the full-screen button only full-screens the video inside the window and does not full-screen the window as well.

**To Reproduce**
1. Get into a voice channel
2. Click on the voice channel
3. Press full-screen button

**Expected behavior**
The window is full-screened as well (as in the official discord client)

**System Info (please complete the following information):**
 - OS: Windows 10 22H2
 - Version: 2.3.0

**Comment by plutonium-239** [comment]
I just stumbled across the plugin that fixes this and will be closing this issue: https://spikehd.github.io/shelter-plugins/dorion-fullscreen/

You can install it from settings > shelter settings > add plugin (i.e. don't need to install locally)

**Comment by plutonium-239** [comment]
It seems this issue is back @SpikeHD 😔
I assume this is because of updating to Tauri 2.0

**Comment by SpikeHD** [comment]
Lol it definitely was, should be fixed in 3cd046ccd17594ac6ceafc9c9d95a9f1ec1df7e2
