### ISSUE TITLE
[Feature Request] Change window control background color

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#172]
**Is your feature request related to a problem? Please describe.**
The background color of the "X" button to close the windows is red.

**Describe the solution you'd like**
I would like the default color for the "X" button to be changed to --danger instead, since it is used in a lot of themes.
![example](https://github.com/SpikeHD/Dorion/assets/91745601/1efcc71f-243c-4a25-af81-3949d84541db)
These two colors should be the same.

**Describe alternatives you've considered**
Can't think of any alternatives.

**Additional context**
I have only been using the Windows version, not Mac or Linux.

**Comment by SpikeHD** [comment]
This would be a good first PR if you'd like to propose the code change yourself!

**Comment by Temanor** [comment]
Sure. It should be simple enough though. I can give it a try, but can't guarantee anything.
