### ISSUE TITLE
[Bug] Duplicated Dorion Settings

### ISSUE THREAD

**Issue by Ztrolix** [SpikeHD/Dorion#175]
**Describe the bug**
Multiple Dorion settings, some settings do not properly work when there is multiple settings.

**Screenshots**
<img width="148" alt="Screenshot 2023-12-24 114051" src="https://github.com/SpikeHD/Dorion/assets/119396780/acd686d1-29a8-4ab5-905c-b4df82596fdd">

**System Info**
 - OS: Windows 11 23H2
 - Version: v3.0.0

**Comment by luximus-hunter** [comment]
Since 3.0.0 Dorion required plugins are hidden. Delete all plugins starting with "Dorion" and that should fix it

**Comment by SpikeHD** [comment]
Above comment is correct ^
