### ISSUE TITLE
[Bug] Voice & Video Settings Panel randomly crashes

### ISSUE THREAD

**Issue by elysiaisalive** [SpikeHD/Dorion#176]
**Describe the bug**
When opening 'Voice & Video' the client will randomly crash

Discord Log attached below;
[log](https://github.com/SpikeHD/Dorion/files/13760728/discord.com-1703385668893.log)

**Comment by SpikeHD** [comment]
Did some fixing on scripts that are pulled from the internet, is this still happening?

**Comment by SpikeHD** [comment]
Closing because I cannot repro/lack of response
