### ISSUE TITLE
[Bug] Automatic Updates stuck

### ISSUE THREAD

**Issue by cozykitten** [SpikeHD/Dorion#177]
**Describe the bug**
For the current update and the last one I get the "Update available" message in Dorion, but after applying the update it still asks to update.

**To Reproduce**
Open App
See Update available message, click on apply update.
See Restart prompt and click on confirm.
App restarts, is the same version as before and asks to update again.

**System Info (please complete the following information):**
 - OS: W11 22H2
 - Version: 2.3.0

**Comment by voytxt** [comment]
Uninstalling Dorion, and then installing the 3.0 version fixed it for me

**Comment by SpikeHD** [comment]
You can also check what the updater is doing by running it manually via commandline with the “—main” flag. If you do that, paste the logs here!

**Comment by cozykitten** [comment]
> Uninstalling Dorion, and then installing the 3.0 version fixed it for me

I could just manually update it, I'm trying to figure out why the auto update isnt working tho

**Comment by cozykitten** [comment]
> You can also check what the updater is doing by running it manually via commandline with the “—main” flag. If you do that, paste the logs here!

running ``dorion.exe --main`` ?
that just starts dorion normally for me and I don't get any output on the terminal.

**Comment by luximus-hunter** [comment]
> running `dorion.exe --main` ? that just starts dorion normally for me and I don't get any output on the terminal.

you need to run the updater with the `--main flag`, so `updater.exe --main`

**Comment by SpikeHD** [comment]
I *believe* the updater was busted in v2.3, and should work in v3 onwards. You'll just have to update manually this time!

**Comment by cozykitten** [comment]
I totally forgot this was a thing... because it worked just fine all the last updates lol
