### ISSUE TITLE
[Bug] Minimize to System Tray not working

### ISSUE THREAD

**Issue by max20091** [SpikeHD/Dorion#180]
**Describe the bug**
Minimize to System Tray not working despite there's a tray icon.

**To Reproduce**
Enable minimize in Settings > Dorion Settings > Minimize to System Tray
**Expected behavior**
Dorion should be minimized to tray when press X button top right.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11 23H2
 - Version: v3.0.0
 - Any other relevant info:

**Comment by luximus-hunter** [comment]
Do you have native titlebar enabled? Currently only Dorions custom titlebar allows for minimize to tray

**Comment by SpikeHD** [comment]
This should be fixed in b2f3211ff4063b83fa390500d1e47c0233e22889 and will be available in the next release!
