### ISSUE TITLE
[Bug] RPC status won't drop after closing the game

### ISSUE THREAD

**Issue by Small-Ku** [SpikeHD/Dorion#181]
**Describe the bug**
Even the registered games setting shows "No game detected", my status still showing previous game.

**To Reproduce**
1. Have ShelteRPC plugin installed and enabled
2. Open a game
3. Close it
4. See the player status in any server

**Expected behavior**
The status should drop after closing the game.

**Screenshots**
Two screenshots while I don't have the app opened already.
![Registered games setting](https://github.com/SpikeHD/Dorion/assets/16464896/d9f7e7e5-124e-4fd6-9a8d-2247e619ec4f)
![RPC status](https://github.com/SpikeHD/Dorion/assets/16464896/2df9f31a-1aaf-44c6-bce7-7e93d19c2026)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v3.1.1
 - Any other relevant info: ShelteRPC plugin enabled

**Additional context**

**Comment by SpikeHD** [comment]
This should be fixed as of bca120a04df0ca0057ad2a78e1a0b190f1a38969 and https://github.com/SpikeHD/rsRPC/commit/4a5a86c878405aa34c8313cb9bf15626c97fc246. Feel free to try a GitHub actions build to verify its working properly now!
