### ISSUE TITLE
[Feature Request] Support for sharing application audio when streaming

### ISSUE THREAD

**Issue by CodeCubeNeo** [SpikeHD/Dorion#186]
It would be awesome to share my screen, but just one app, not the whole screen and still be able to play the application audio. Awesome app by the way. I guess this is already planned, or you can just close this issue. This functionality is in the original discord client yes?

**Comment by SpikeHD** [comment]
This is something that exists in regular Discord yes, but since Webview2 is a closed platform I can't just, like, fork and fix it unfortunately. I think this is related enough to #153 (which I think you've seen) that I will close this and just append 'window audio' to the title of that issue.
