### ISSUE TITLE
[Bug] ClientTheme Plugin in Vencord doesn't work

### ISSUE THREAD

**Issue by KonerDev** [SpikeHD/Dorion#191]
**Describe the bug**
The ClientTheme plugin in Vencord doesn't work.

**To Reproduce**
1. Install Vencord in Dorion
2. Activate the ClientTheme plugin
3. In the settings of the plugin, set the color to for example `#121212`

**Expected behavior**
Discord's background color should change to the color previously set in the settings of the plugin, but it doesn't change.

**System Info (please complete the following information):**
 - OS: Windows 11
 - Dorion Version: V4.0.1
 - Chromium 120
 - Vencord D73790e (Web)

**Comment by SpikeHD** [comment]
This should be fixed as of f7ecb7e, you can try an actions build if you want it now, otherwise it will be available in the next release!
