### ISSUE TITLE
Toggle not disabled when greyed out [Bug]

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#192]
**Describe the bug**
When you have "Notify me of updates" enabled and turn on autoupdates, "Notify me of updates" gets greyed out, but it doesn't switch between on and off.

**To Reproduce**

 - Go to Dorion settings
 - Enable "Notify me of updates"
 - Turn on autoupdates
 - Do the same with "Notify me of updates" turned off

**Expected behavior**
When you have "Notify me of updates" enabled then switch on autoupdates, the "Notify me of updates" toggle should be disabled and greyed out. Not just greyed out.

**Screenshots**

https://github.com/SpikeHD/Dorion/assets/91745601/c027c9c2-1e43-495f-bde5-7762b7cd72f1

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v4.1.0

**Additional context**
This is assuming "Notidy me of updates" and autoupdate doesn't work together. I don't see why "Notify me of updates" would be greyed out if it was.

**Comment by Temanor** [comment]
I know it's just visual, but I think it should be changed so that it is more clear that it has been disabled.
When disabling autoupdate, it could maybe re-enable the toggle, or it might just be better to keep it disabled.
Idk :/

**Comment by SpikeHD** [comment]
Imo it should be clear enough already, as this signals to the user “This option is now disabled as a result of another option choice, but if you were to enable that other option choice again, it will keep the now-disabled choice at where you last set it” but thats just me, I’m no UX/UI designer. It also may be confusing to people who redisable autoupdate and have Notify “randomly” switch back on

**Comment by Temanor** [comment]
Say you have a toggle for permissions for an app where there is 2 toggles. One for allowing gps and one for sending geo location data. If the sending geo location data is turned on, so would the gps access toggle. And if gps is turned off, so would location data. That way it would indicate to the user that gps in needed for location data to work.
Of course, this is not quite the same as in Dorion, but it will be easier to understand than if the location data toggle still says it's on, but you can't toggle it because gps access is not turned on.
I'm not a UI/UX designer either, but I think this would be better than your solution.

**Comment by Temanor** [comment]
But then again, it's your project. You do you.
