### ISSUE TITLE
[Bug] Can't turn off hardware acceleration

### ISSUE THREAD

**Issue by headquarter8302** [SpikeHD/Dorion#193]
**Describe the bug**
In the performance setting of Dorion, disable hardware acceleration cannot be toggled on.

**To Reproduce**
1. Go to the Performance & Extras tab on settings.
2. Try to toggle Disable Hardware Acceleration on.

**Expected behavior**
The toggle to be, toggleable, and hwaccel to be turned off, probably after a restart.

**Screenshots**
![Screenshot 2024-01-15 075316](https://github.com/SpikeHD/Dorion/assets/65797058/db87d6b2-8877-4cd8-acde-5555d45513ba)

**System Info (please complete the following information):**
 - OS: Windows 10 version 22H2 (OS Build 19045.3930)
 - Version: v4.1.0
 - Any other relevant info: Has been happening since v4.0.1

**Additional context**
My Dorion client is untouched. I haven't done any modding or plugins or theming yet.

**Comment by SpikeHD** [comment]
Should be fixed as of https://github.com/SpikeHD/shelter-plugins/commit/af1cc6f9bafb607f8b188dfef5180ba5818a8256. Shelter plugins are autoupdated on load, so there's no need to wait for a new Dorion release 👍
