### ISSUE TITLE
[Bug] [Priority: HIGH] Windows Defender flags (false) Trojan in Dorion v4.1.0 

### ISSUE THREAD

**Issue by plutonium-239** [SpikeHD/Dorion#196]
**Describe the bug**
Just updated to v4.1.0, and windows defender has flagged Dorion as carrying a trojan:

The trojan is called "Bearfoos.a!ml". The "ml" at the end specifies that it was detected through machine learning and might be a false positive, which it seems to be in this case. 

@SpikeHD could you please make sure this is the case?

To not cause any panic, here is a VirusTotal scan of Dorion.exe which shows no threats: https://www.virustotal.com/gui/file/d9ea7d2456e033f973e61342c23e4b1b2c77d05abf126503baddd92bb6ccec73?nocache=1

**To Reproduce**
Download/update to v4.1.0

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/29684689/4b64a701-6f17-4956-8ffc-c55f8e5153ef)

**System Info:**
 - OS: Windows 10
 - Version: v4.1.0

**Comment by Temanor** [comment]
If you run a program through virustotal and don't get any detections, it is basically guaranteed to be safe. As long as you get it from the official GitHub and not some random file someone sent you through DMs you will be fine.

**Comment by SpikeHD** [comment]
Yes this has been happening for a while, see #182, its a false positive and the only things I can do are submit the files to MS on every update, and have more people use Dorion so Defender learns that its fine.
