### ISSUE TITLE
[Bug] No File Content Preview

### ISSUE THREAD

**Issue by Desapressad0x** [SpikeHD/Dorion#201]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would be cool to see the file content preview like in default Discord.

**Describe alternatives you've considered**
.

**Additional context**
Uploaded files are always only downloadable attachments, no previews.

**Comment by SpikeHD** [comment]
Fixed as of 8754f1324caf9fcfab9bf84a5aa13d94feb6282c, if you want to use the fix now you can [download an Actions build](https://github.com/SpikeHD/Dorion/actions/runs/7768622667)
