### ISSUE TITLE
[Feature Request] Reduce captchas when accepting server invites

### ISSUE THREAD

**Issue by Desapressad0x** [SpikeHD/Dorion#202]
**Is your feature request related to a problem? Please describe.**
A considerable number of captchas occur when trying to accept invitations.

**Describe the solution you'd like**
Spoof the WebView User-Agent to a Discord-default one to reduce captchas when accepting server invites.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by luximus-hunter** [comment]
Just an update: looking into this

**Comment by SpikeHD** [comment]
Is this still a problem? I don't think I've ever experienced this issue

**Comment by piotr25691** [comment]
not for me, i only get captchas when performing actions like inviting bots

for server joins i don't get that

**Comment by SpikeHD** [comment]
Mkay, I'll close this for now. If someone else has this issue, maybe post a video or something 👍
