### ISSUE TITLE
[Bug] Discord doesn't screenshare sucsessfully on windows 7

### ISSUE THREAD

**Issue by MacncheeseTTR** [SpikeHD/Dorion#203]
**Describe the bug**
Discord won't screenshare correctly with hardware acceleration off or on.

**To Reproduce**
Go on windows 7, login with dorion, and start screensharing.

**Expected behavior**
The screenshare should not be stuck on loading.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/132606248/05402765-f386-4ebe-9ed6-055f8d061072)

**System Info (please complete the following information):**
 - OS: Windows 7 pro, installed on a gpt partiton, with UEFI
 - Version: v4.1.1

**Comment by SpikeHD** [comment]
WebView2 (the engine Dorion uses on Windows), as like most software, has ended support for Windows 7. Dorion does not *explicitly* support Windows 7 either and never will. Most of it happens to work fine, but any Win7 specific issues will not be receiving support.

**Comment by MacncheeseTTR** [comment]
Weird. It was just working yesterday so maybe a restart will help
