### ISSUE TITLE
[Bug] Reopening Dorion in settings page causes weird buttons to appear

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#206]
**Describe the bug**
When reopening Dorion while having the settings page open, buttons will appear next to each header except the top one.

**To Reproduce**
Open settings page
Minimize the window
Open the window again

**Expected behavior**
The page should look the same as when you closed it.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/91745601/94fa4080-4646-4a75-9fdb-8ef91baacd1e)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v4.1.2

**Additional context**
Seems to be the buttons that appear above and below scrollbars.
When you click them, the header will move slightly up and down.

**Comment by luximus-hunter** [comment]
This issue continues to the chat. It has to do with scrollbar behavior.

![image](https://github.com/SpikeHD/Dorion/assets/49814847/df6c0592-b0be-4501-9578-6e0a451bb9fc)

**Comment by SpikeHD** [comment]
I haven't seen this in a while, is this still happening?

**Comment by Temanor** [comment]
No. I can't seem to reproduce it anymore.
