### ISSUE TITLE
[Bug] Icon in system tray is not changing with notifications

### ISSUE THREAD

**Issue by Nikodemsky** [SpikeHD/Dorion#209]
**Describe the bug**
I'm not sue if it's missing feature, bug or something related to https://github.com/SpikeHD/Dorion/issues/27 but icon on the system tray doesn't change with notifications - it's always the same.

**To Reproduce**
Just get any type of notification.

**Expected behavior**
The icons should change just like the icon in taskbar.

**Screenshots**
![112](https://github.com/SpikeHD/Dorion/assets/14090596/ff6e4870-f518-4766-a991-87d82679064e)
![222](https://github.com/SpikeHD/Dorion/assets/14090596/3bb7c80f-8cd7-4444-9206-ea151983a551)

**System Info (please complete the following information):**
 - OS: Win10 Pro 22H2
 - Version: 4.1.2

**Comment by SpikeHD** [comment]
Added in ce165e3 and will be available in the next release 👍
