### ISSUE TITLE
[Bug] Vencord Themes are bugged

### ISSUE THREAD

**Issue by QueenlyQuester** [SpikeHD/Dorion#212]
**Describe the bug**
If I tried to “load” themes into Vencord. The theme I wanted to load was midnight, I activated it, and it didn't show up.
**Expected behavior**
The whole UI of discord should be rounded.

**Comment by Temanor** [comment]
Don't use Vencord to load themes. Use the themes tab under the Dorion section.

**Comment by QueenlyQuester** [comment]
Well, thank you for pointing that out, I figured it out a couple of minutes later after having reported it.
