### ISSUE TITLE
[Feature Request] Better app icon for macOS

### ISSUE THREAD

**Issue by FormalSnake** [SpikeHD/Dorion#213]
**Is your feature request related to a problem? Please describe.**
The current app icon on macOS is very ugly and not fitting, like Notion lol.
<img width="566" alt="Screenshot 2024-03-03 at 17 58 06" src="https://github.com/SpikeHD/Dorion/assets/90651091/81e491d2-e4cd-43f2-bee1-433f9e2a9819">
If you look here Dorion looks very out of place.

**Describe the solution you'd like**
A new app icon for macOS

**Describe alternatives you've considered**
Setting it using finder doesn't work.

**Additional context**
Here is a design I made.
![Dorion](https://github.com/SpikeHD/Dorion/assets/90651091/f8796b68-a098-4abe-a4e5-a707d5477e38)

**Comment by SpikeHD** [comment]
Idk about you, but I feel like the icon fits in just fine alongside the likes of Spotify and Windscribe:

<img width="521" alt="image" src="https://github.com/SpikeHD/Dorion/assets/25207995/a7724be0-11b0-437f-a709-d51e73848393">

**Comment by FormalSnake** [comment]
It's mainly for OCD reasons, I want to have almost all icons have the same shape at least when they're in my dock.
It looks too much like a windows icon honestly, so it would be nice for it to follow the apple guidelines a bit.
And Tauri does allow for platform specific icons, just replace the icns one.
https://tauri.app/v1/guides/features/icons/

**Comment by SpikeHD** [comment]
Seeing as this is mostly preferential, and the current icon isn't egregious compared to other MacOS icons, I won't be implementing this.

You can customize it yourself (as you've mentioned) if you'd like, and to get it to work properly you just need to remove it from the dock and re-add it after you've changed the icon.

**Comment by FormalSnake** [comment]
> Seeing as this is mostly preferential, and the current icon isn't egregious compared to other MacOS icons, I won't be implementing this.
> 
> 
> 
> You can customize it yourself (as you've mentioned) if you'd like, and to get it to work properly you just need to remove it from the dock and re-add it after you've changed the icon.

It reverts on app launch for me.
