### ISSUE TITLE
[Bug] Application glitched into one corner.

### ISSUE THREAD

**Issue by Ztrolix** [SpikeHD/Dorion#215]
**Describe the bug**
The entire window becomes a single color and the window is very small then after a few seconds Dorion crashes.

**To Reproduce**
1. Minimize Dorion
2. Done

**Expected behavior**
The Dorion application will become all glitched into one corner.

**Screenshots**
![Screenshot 2024-03-16 103325](https://github.com/SpikeHD/Dorion/assets/119396780/539a8c2a-d08e-48a7-ada1-812ef03ab512)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v4.1.3

**Comment by SpikeHD** [comment]
Well I know about the briefly small visual bug, but I can't say I've seen it crash because of it before. Does turning on "Use Native Titlebar" help at all?

**Comment by Ztrolix** [comment]
Uhh.. Yes it does.
