### ISSUE TITLE
[Bug] Can't access Dorion settings after enabling Vencord

### ISSUE THREAD

**Issue by catalin560** [SpikeHD/Dorion#217]
go to Dorion Plugins >
turn on Vencord and restart Dorion >
can't access any of the tabs under Dorion or Shelter sections and all I see is this toast notification:
![Capture](https://github.com/SpikeHD/Dorion/assets/22744333/7059587e-bc52-44ed-a535-74b8bd4e0e0c)

Windows 10
Dorion v.4.1.3

**Comment by SpikeHD** [comment]
Thanks for letting me know! Seems like Vencord now has some sort of incompatibility or something:
![image](https://github.com/SpikeHD/Dorion/assets/25207995/de1357e1-962d-4dad-8d26-322233bc9766)

In the meantime, for anyone stuck here, you can open Dorion's config (`%appdata%/dorion/config.json` for Windows) and remove Vencord from the "client_mods" list, and then restart.

**Comment by SpikeHD** [comment]
[Made a PR for Shelter](https://github.com/uwu/shelter/pull/26) that solves this. Once a solution is in place, Dorion + Vencord should just automagically start working again 👍

**Comment by SpikeHD** [comment]
This should be fixed now!
