### ISSUE TITLE
[Bug] Windows 11: Opening from minimized state via taskbar moves the window to the main monitor

### ISSUE THREAD

**Issue by RandomClaim** [SpikeHD/Dorion#219]
**Describe the bug**
When I have the Dorion window open on my 2nd Monitor (the one not declared as "Main display"), then minimize (taskbar or titlebar) and un-minimize (via taskbar or tray) the window opens on my main display.

**To Reproduce**
1. Have Dorion open on non-main display
2. *Minimize* Dorion (**not** closing to tray, that works fine)
3. Reopen the window and it moves to another monitor

**Expected behavior**
The window should always re-appear on the screen from where it was minimized.,

**Screenshots**

[2024-04-04 20-21-10(1).webm](https://github.com/SpikeHD/Dorion/assets/9338392/2660f82a-a735-40a5-b616-a6c6b405bde8)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v4.1.3
 - Any other relevant info: 

**Additional context**
- I have no clue if this could be fixed by changing some setting in windows
- Only happens when minimizing to taskbar. Closing to tray is fine

**Comment by SpikeHD** [comment]
I believe this was fixed as of 535961e, feel free to try and [Actions build](https://github.com/SpikeHD/Dorion/actions) and let me know if it's still busted
