### ISSUE TITLE
[Feature Request] [bug] fix the theming for the title bar

### ISSUE THREAD

**Issue by Scrapper1824** [SpikeHD/Dorion#222]
**Is your feature request related to a problem? Please describe.**
can you fix the theming for the title bar

**Describe the solution you'd like**
I was hoping you could fix the theming for the title bar so the theme can change the theme of the title bar

**Additional context**
![Screenshot 2024-04-16 222721](https://github.com/SpikeHD/Dorion/assets/72410525/8ab3f615-f554-4754-8d24-6626857f0cc0)
![Screenshot 2024-04-16 222727](https://github.com/SpikeHD/Dorion/assets/72410525/e644cb30-b9b2-4254-9eff-39e044d87264)

**Comment by Scrapper1824** [comment]
the midnight title bar is the midnight theme on vencord

**Comment by SpikeHD** [comment]
To do this would require setting the top bar classes to the Discord ones, which is a pain in the ass to maintain whenever Discord updates as Discord updates change these class names. To update these class names for everyone requires a full new release, which is a waste of time for everyone 😄.
