### ISSUE TITLE
[Bug] Detected as Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by PhilJbt** [SpikeHD/Dorion#226]
**Describe the bug**
_Microsoft Defender_ detect _Dorion_ as **Trojan:Script/Wacatac.B!ml**

**Screenshot**
![dorion](https://github.com/SpikeHD/Dorion/assets/22506952/44df57b3-b494-40fd-b973-2a119fc340de)

**System Info (please complete the following information):**
 - OS: Microsoft Windows 10 Family (10.0.19045)
 - Version: 4.2.0

**Comment by Temanor** [comment]
False positive. Has been reported before.

**Comment by PhilJbt** [comment]
> False positive. Has been reported before.

Yes, I can imagine. It might be a good idea to send the new binary to the most widely used antivirus programs on the market with each new iteration. I know it's a lot of work, having done it myself in the past.
