### ISSUE TITLE
[Bug] Windows Defender detected Trojan:Script/Wacatac.B!ml on Dorion executable

### ISSUE THREAD

**Issue by headquarter8302** [SpikeHD/Dorion#227]
**Describe the bug**
While running the program, Windows Defender suddenly kicked in and flagged the executable as a severe malware under the `Trojan:Script/Wacatac.B!ml` definition. This also immediately killed the client.

**To Reproduce**
While I can't reproduce the issue anymore, this is how it got flagged:
1. Open Dorion.

**Expected behavior**
The program to run normally

**Screenshots**
![Screenshot 2024-04-24 045534](https://github.com/SpikeHD/Dorion/assets/65797058/3bd86c83-5c5a-44a7-ad7f-4f8214734406)

**System Info (please complete the following information):**
 - OS: Windows 11 2261.ni_release.220506-1250
 - Version: v4.2.0

**Additional context**
Programs are often flagged as `Trojan:Script/Wacatac.B!ml` due to them using specific compiler flags/instructions, I am wondering if you are using any that affects it

**Comment by SpikeHD** [comment]
See #226, #196, or #182. Also see the note in [the "Download" section of the README](https://github.com/SpikeHD/Dorion?tab=readme-ov-file#download).

Dorion seems to live in Defenders head rent-free for some reason, and its had problems with it for many months lol. I don't plan to sign the `.exe` with Microsoft or something anytime soon, so users are encouraged to do VirusTotal scans of the program before they use it.

As for compiler flags, Dorion doesn't use anything special except for [stripping debug info and enabling link-time optimizations](https://github.com/SpikeHD/Dorion/blob/aea48562f770d1cbdb68a47f0c2983d3f96724af/src-tauri/Cargo.toml#L14).

**Comment by headquarter8302** [comment]
Whoops, I didn't see any of those other issues, sorry
