### ISSUE TITLE
[Bug] No audio

### ISSUE THREAD

**Issue by netcore10** [SpikeHD/Dorion#228]
**Describe the bug**
output volume silent, no matter device selected. For some reason it's the only client that does this. I can't click reset voice settings, can't hear pings, can't hear any sfx.

**System Info (please complete the following information):**
latest windows 11 and dorion.

**Comment by SpikeHD** [comment]
Is this still happening? I can't say I've heard of anyone else with this issue, and I've never encountered it personally. Do you have a weird audio device setup or something?

**Comment by netcore10** [comment]
it is indeed still happening. It had sound on the first install but bugged out when i went into settings. No weird device setup, just realtek audio

**Comment by netcore10** [comment]
though, it could be something involving my system i just don't know

**Comment by netcore10** [comment]
I reinstalled 3 times and it kicked in. was probably a weird data problem.

**Comment by SpikeHD** [comment]
Weird, glad it's fixed though!
