### ISSUE TITLE
[Bug] Vencord badge images don't load

### ISSUE THREAD

**Issue by Desapressad0x** [SpikeHD/Dorion#229]
**Describe the bug**
Vencord custom badges don't loading.

**To Reproduce**
Steps to reproduce the behavior: Opening the profile of a person who owns a custom vencord badge.

**Expected behavior**
The custom badge being shown.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/59629875/0248dd77-337f-416d-a5c4-2680ad7cd56d)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: 4.2.0
 - Any other relevant info: 

**Additional context**
Badge link: https://badges.vencord.dev/badges/687022032726392839/1-58651ad30489b5f1c03a9e2eec4a835ddb3a0fed.png
Console error: `Refused to load the image 'https://badges.vencord.dev/badges/687022032726392839/1-58651ad30489b5f1c03a9e2eec4a835ddb3a0fed.png' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: https://*.discordapp.net https://*.discordapp.com https://*.discord.com https://i.scdn.co https://i.ytimg.com https://i.imgur.com https://media.tenor.co https://media.tenor.com https://c.tenor.com https://*.youtube.com https://*.giphy.com https://static-cdn.jtvnw.net https://pbs.twimg.com https://assets.braintreegateway.com https://checkout.paypal.com https://c.paypal.com https://b.stats.paypal.com https://slc.stats.paypal.com https://hnd.stats.paypal.com https://api.cash.app".`

**Comment by SpikeHD** [comment]
This is unfixable*, as the web engine Dorion uses cannot overwrite CSP headers
