### ISSUE TITLE
AUR package for Arch Linux-based distros? 

### ISSUE THREAD

**Issue by Impeta** [SpikeHD/Dorion#23]
Title says it all. Alternatively, Appimage would be just as good!

**Comment by SpikeHD** [comment]
Actions should now produce:

* Windows `.msi`
* Windows Portable
* Linux `.deb`
* Linux `.AppImage`
* Linux portable
* ~~MacOS Universal Bundle~~ (maybe one day :P)

AppImage is untested right now so if something is funky with it lemme know and I can see about fixing it!
