### ISSUE TITLE
[Feature Request] Add accent color CSS property

### ISSUE THREAD

**Issue by maicol07** [SpikeHD/Dorion#230]
**Is your feature request related to a problem? Please describe.**
Accent color in a CSS property so themes can use it.

**Describe the solution you'd like**
A CSS property that stores the accent color value and updates it when it changes.

**Describe alternatives you've considered**
Manual accent color via CSS

**Additional context**
BetterDiscord implementation: https://github.com/BetterDiscord/BetterDiscord/pull/1663
Tauri idea: https://github.com/tauri-apps/tauri/discussions/5305

**Comment by maicol07** [comment]
@SpikeHD I've tried the accent colour CSS property, and it works fine. The only issue I've found is that changing the accent colour at runtime when Dorion is opened doesn't update the property until a reload. There's this that you can use to listen for changes; however, I don't know Rust, so I don't know how to use it: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/constant.WM_DWMCOLORIZATIONCOLORCHANGED.html

**Comment by SpikeHD** [comment]
Yea its still WIP, features like that will be included but they just aren't right now, that's why I left this issue open 👍

**Comment by maicol07** [comment]
Another thing to add is multiple variables for different formats (i.e. rgb, hsl, ...)

**Comment by SpikeHD** [comment]
I will only be including the one variable in hex format. From my knowledge, CSS functions that take colors will accept any format, and hex supports alpha values just like RGBA, so it shouldn't really matter which format is used nor would it be very useful to have other formats available.

**Comment by yavko** [comment]
I started work on a rust library for getting accent colors (converts to RGB, not RGBA cuz alpha is useless and used nowhere), that works so far on linux (through xdg-desktop-portal), and windows. I'm finishing up windows, support and will also get macOS support working too. So maybe it could be used to add support for this.

**Comment by SpikeHD** [comment]
That sounds great! Looking forward to it 👍

**Comment by yavko** [comment]
> That sounds great! Looking forward to it 👍

Got windows working finally, but it's kinda scuffed. Also, I'm thinking of making the color format be a `0.0-1.0` scale, instead of `0-255`, cuz the linux api uses that, and converting to 0-255 has a loss of detail, but idk if I should do it or not
![image](https://github.com/SpikeHD/Dorion/assets/15178513/f57317e0-6e95-4b86-8492-3cd3b397e44f)

**Comment by yavko** [comment]
Having trouble with macOS, rn I can only get the accent color, and not listen to it.

**Comment by yavko** [comment]
> Having trouble with macOS, rn I can only get the accent color, and not listen to it.

I now know the issue was that I was using the `NSDistributedNotificationCenter` incorrectly, but for now, I've implemented a busy loop, which is inefficient (it's the same as what the `dark-light` crate is doing), but it works for the time being :). I'll probably get the crate published sometime soon. And it can be implemented in Dorion then after.

**Comment by yavko** [comment]
seems a crate with working macOS exists, so it could be used instead lol https://github.com/bash/mundy/tree/main

**Comment by SpikeHD** [comment]
Full accent color support, including updating on the fly, is now finished as of 92e300202e1f7f7563e7f6a609b34a20be841abe and will be available in the next release!
