### ISSUE TITLE
[Bug] Link to separate channel in dm opens the channel in both the browser and Dorion

### ISSUE THREAD

**Issue by Demopans** [SpikeHD/Dorion#231]
**Describe the bug**
 Link to separate channel in dm opens the channel in both the browser and Dorion when formatted as `[text](link)`

**To Reproduce**
format a link to any random server you are in as `[text](server link)`

**Expected behavior**
Same behavior as using naked server link

**Screenshots**
See video

https://github.com/SpikeHD/Dorion/assets/22843987/0b692453-8864-4236-a113-699a126308a2

**System Info (please complete the following information):**
 - OS: Win 10
 - Version: [e.g. v4.2.1]
 - Any other relevant info: 

**Additional context**

**Comment by Banaanae** [comment]
Server links look like this `https://discord.com/channels/SERVERID/CHANNELID/MESSAGEID`
For example `https://discord.com/channels/1128909403672821811/1128911050117488640/1157211420732166225` click this in dorion to replicate

**Comment by Demopans** [comment]
Yes, that works as normal. I'm referring to such links formatted using markdown 
Try `[link](https://discord.com/channels/1128909403672821811/1128911050117488640/1157211420732166225)` to see the difference in Dorion compared to the native app or the mobile app

**Comment by SpikeHD** [comment]
Should be fixed in 4c44d8d and will be available in the next release!
