### ISSUE TITLE
[Feature Request] Revamped logo / Custom icon support

### ISSUE THREAD

**Issue by 27rogi** [SpikeHD/Dorion#233]
**Is your feature request related to a problem? Please describe.**
Request is only related to design choise for the logo.

**Describe the solution you'd like**
I really like this application and use it as main Discord client, yet I think there's a gap between original client icon design and the one used in Dorion. I decided to design some concept logos that still feature `D` and `o` combination with **D** being the main point of change, I decided to give it more sleek look and sharp edges that demonstrate speed/motion, because Dorion is very speed/performance oriented.

**Describe alternatives you've considered**
Icon can be changed personally to anything user will like via settings (custom icon support)

If needed I can provide fully separated SVG logo files, due to GitHub limitations I'm unable to upload the archive.
![dorion_full](https://github.com/SpikeHD/Dorion/assets/10144091/1ec026da-df6f-4af5-a4c1-6bcd76b35788)

**Comment by SpikeHD** [comment]
While I'm not opposed to an icon change (specifically middle-bottom would probably be what I prefer, but I'd have to ask other people for thoughts), all major OS support changing the icon of applications:
* Windows: Right click executable -> Properties
* MacOS: Right click -> Get Info -> Drag icon file over existing icon
* Linux: Probably depends on what you're using so you'd have to google it

**Comment by SpikeHD** [comment]
I've asked a couple people, they agree that the middle-bottom one is the best. I'm curious how it'd look with the same "drop shadow" effect as the current icon, since I've always liked it, so if you're able to recreate it with that effect I'd love to see it as well!

You can also make a PR to change the icons by doing the following, when you're ready:

1. Fork this repo
2. Clone your fork
3. Put your HQ `icon.png` in the root of the folder
4. Run `pnpm install` (or `npm install` or whatever you prefer)
5. Run `pnpm tauri icon -o src-tauri/icons/ icon.png`, it should generate all the required icons and replace the old ones (see the [Tauri icon docs](https://tauri.app/v1/guides/features/icons/)

**Comment by 27rogi** [comment]
> I've asked a couple people, they agree that the middle-bottom one is the best. I'm curious how it'd look with the same "drop shadow" effect as the current icon, since I've always liked it, so if you're able to recreate it with that effect I'd love to see it as well!
> 
> You can also make a PR to change the icons by doing the following, when you're ready:
> 
> 1. Fork this repo
> 2. Clone your fork
> 3. Put your HQ `icon.png` in the root of the folder
> 4. Run `pnpm install` (or `npm install` or whatever you prefer)
> 5. Run `pnpm tauri icon -o src-tauri/icons/ icon.png`, it should generate all the required icons and replace the old ones (see the [Tauri icon docs](https://tauri.app/v1/guides/features/icons/) if you need more detail)

Thanks for the detailed instructions. I will try to recreate your idea once I get spare time!

**Comment by Temanor** [comment]
I agree that the middle bottom one looks best, but I am curious what it would look like with the drop shadow effect and possibly more rounded corners.

**Comment by 27rogi** [comment]
@SpikeHD I got few minutes to make some examples with shadows, some copying original shadow idea and others are more playful with it, to see which is most optimal. Because if some flat element has shadow it might get harder to recognize once element is smaller (for example tray icon / taskbar icon). Also latest one is an experiment which implies idea of more rounded corners by @Temanor, if I understood him correctly 😅 

![dorion_shadow_all](https://github.com/SpikeHD/Dorion/assets/10144091/0ed4e9ac-bce1-4fde-acc7-f72d6ebc69d6)

**Comment by Temanor** [comment]
Personally, I like the bottom right one the most.

And yes, you understood exactly what I was thinking :)

**Comment by SpikeHD** [comment]
Looks awesome! I think I lean most towards the top right one, so if you'd like to make a PR with that new icon using those instructions, we can have that in for the next release  :+1:

**Comment by sakgoyal** [comment]
I know this is old now, but would it be possible to make the blue color a bit darker? it has relatively low contrast at the moment so its hard to easily see what the icon is on the taskbar. I am slightly colorblind so its very washed out. 

Especially on a higher res monitor where the icons get a bit small on the taskbar, its very difficult to see clearly.

**Comment by SpikeHD** [comment]
Though, custom icons are still supported on the OS-level, you are welcome to darken it yourself and look up how to change the icon on your respective OS

**Comment by 27rogi** [comment]
> I was never given the PSD (or whatever file they used for whatever program) so unfortunately I can't edit it properly (and I don't know anything about colors and art lolol). If the original creator happens to see this and they want to remake it with different colors, I can consider it 👍

Hi. I made the logo design using Figma, also the attached file in this issue already in SVG format, so it can be simply downloaded and edited using any vector editor.
