### ISSUE TITLE
[Feature Request] Add drop shadow to window

### ISSUE THREAD

**Issue by jamesWalker55** [SpikeHD/Dorion#234]
**Is your feature request related to a problem? Please describe.**
On Windows, the Dorion window does not have a drop shadow. This makes it hard to see the edges of the window if Dorion happens to be on top of another window of a similar color.

**Describe the solution you'd like**
Add drop shadows to the window. For Tauri there is a plugin for this: https://github.com/tauri-apps/window-shadows 

**Describe alternatives you've considered**

**Additional context**

**Comment by SpikeHD** [comment]
Added in 1456baa2548f7ae8ae0dd3b862d53d7a0ce374d1, and will be available in the next release
