### ISSUE TITLE
[Feature Request] Ability to adjust font size

### ISSUE THREAD

**Issue by khewweifeng** [SpikeHD/Dorion#238]
**Is your feature request related to a problem? Please describe.**
`
Not related to a problem
`

**Describe the solution you'd like**

`
Ability to adjust font size with keyboard shortcut / mouse scrollwheel
`

**Describe alternatives you've considered**

`
Ability to adjust font size with keyboard shortcut / mouse scrollwheel
`

**Additional context**

**Comment by SpikeHD** [comment]
While the UI is a little broken for some reason (it's supposed to have tickmarks and and percentage labels, will investigate soon), this slider in Dorion Settings adjusts the zoom level of the application:
![image](https://github.com/SpikeHD/Dorion/assets/25207995/251e64e3-b187-4619-8df6-c7fe0d2b0398)

I will consider adding a keyboard shortcut, but no promises

**Comment by khewweifeng** [comment]
> While the UI is a little broken for some reason (it's supposed to have tickmarks and and percentage labels, will investigate soon), this slider in Dorion Settings adjusts the zoom level of the application: ![image](https://private-user-images.githubusercontent.com/25207995/339459215-251e64e3-b187-4619-8df6-c7fe0d2b0398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTY3ODAsIm5iZiI6MTcxODI5NjQ4MCwicGF0aCI6Ii8yNTIwNzk5NS8zMzk0NTkyMTUtMjUxZTY0ZTMtYjE4Ny00NjE5LThkZjYtYzdmZTBkMmIwMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyN2QyYjBkYjI4NTlhNWFjMjkwZmJjZWExMDMxMDQxZmRmZDhiOGZhNDAyYTYwNDdlOWQ0NmUwY2U5NTYwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7PtK5spxb3UhZ2xHqKRMPQliUGwZjbhr1Nci7RF0uAo)
> 
> I will consider adding a keyboard shortcut, but no promises

Thanks, I can use this 🙂
