### ISSUE TITLE
[Feature Request] Right click able to copy video media link (shelter mod)

### ISSUE THREAD

**Issue by khewweifeng** [SpikeHD/Dorion#239]
**Is your feature request related to a problem? Please describe.**

> Currently in Dorion, you can view image with left click and right click to copy image link but this does not apply for video media.

**Describe the solution you'd like**

>Able to copy video media link and paste to anywhere like official discord client

**Describe alternatives you've considered**

>Anything that can copy link into clipboard 

**Additional context**

>Video didn't have the option to copy link, please refer to below attached photo. 

![image](https://github.com/SpikeHD/Dorion/assets/54496743/8cd1b811-3a40-441e-8746-29c2ab3a0ae7)

**Comment by SpikeHD** [comment]
I don't know about you but I see a "Copy Link" button right there in the screenshot :P

**Comment by khewweifeng** [comment]
Let me clarify this, in the screenshot was gif but when comes to mp4, webp format... It doesn't have that option On 16 Jun 2024 1:23 am, SpikeHD ***@***.***> wrote:
I don't know about you but I see a "Copy Link" button right there in the screenshot :P

**Comment by BrennanAyers** [comment]
I'm not entirely sure if it's how Dorion is handling the view, if something changed with Edge(?), or Discord itself changed how it works. What I do know is that it was working prior, and then I updated Dorion to 5.0.1 and it borked 🙃 
It seems to be some sort of mismatch on how to handle right clicks, whether they're a Discord Context right click or a Web Browser Right Click. 
Discord Desktop: 
![image](https://github.com/SpikeHD/Dorion/assets/45154998/b6b52496-8497-4a8a-acdc-795f64fcb6ef)
Dorion:
![image](https://github.com/SpikeHD/Dorion/assets/45154998/7ae76e73-db24-49cb-a8a5-2cb8d4dc6d3e)
Web Client (Firefox):
![image](https://github.com/SpikeHD/Dorion/assets/45154998/d659673b-7b67-40cb-8ec4-fb945f833128)
Upon checking all 3 I'm inclined to believe it's how the web client is set up now, which is probably worse and more unfortunate. 

The loss of contextual menus can also be seen with URLs:
Desktop: 
![image](https://github.com/SpikeHD/Dorion/assets/45154998/693d9f5c-5677-432e-aac4-6309452301eb)
Dorion/Web Client:
![image](https://github.com/SpikeHD/Dorion/assets/45154998/04ccb5b8-d6b1-4464-894a-9ec9653ee6ec)

And the text input box:
Desktop:
![image](https://github.com/SpikeHD/Dorion/assets/45154998/a0b5cac1-839e-4fef-b983-a7bd2cb22bf3)
Dorion/Web Client:
![image](https://github.com/SpikeHD/Dorion/assets/45154998/1f01d82d-a028-47ad-bd10-f41ff9d448c8)

Wondering if this functionality returning will have to fall to a plugin. Thanks.

**Comment by SpikeHD** [comment]
Great investigation! Yea, it looks like they differentiate now. It's especially evident since the menu items' actions pass a string that specifies `web_`:

![image](https://github.com/SpikeHD/Dorion/assets/25207995/9be80d72-a7f9-4390-864e-50a4b08fe677)

Weird nerf tbh. This could *probably* be brought back in a plugin but I haven't taken a deep dive yet.

**Comment by SpikeHD** [comment]
Oh! [Vencord](https://github.com/Vendicated/Vencord/blob/main/src/plugins/webContextMenus.web/index.ts) has a plugin that does this already. Can probably just see what it does and reimplement it shelter style.

**Comment by khewweifeng** [comment]
Hi, I think I found alternative way to achieve the right click copy link, you need to enabled vencord in dorion settings > client mods & plugins and restart dorion.

**Comment by khewweifeng** [comment]
> Oh! [Vencord](https://github.com/Vendicated/Vencord/blob/main/src/plugins/webContextMenus.web/index.ts) has a plugin that does this already. Can probably just see what it does and reimplement it shelter style.

Thanks, I will use this first

**Comment by BrennanAyers** [comment]
oh, huh, I didn't see that plugin earlier. Thanks!

**Comment by SpikeHD** [comment]
I have gone over this again and the work involved to recreate something that already exists as a Vencord plugin doesn't feel worth my time. If someone else wants to make a Shelter-based context menu plugin, feel free to open a PR to add it as a [default plugin](https://github.com/SpikeHD/Dorion/blob/738b9c0dc33f29ef39b08237b1b0e17e27e8eaa1/src-tauri/injection/shared/plugins.ts#L2) in Dorion!
