### ISSUE TITLE
Selection box for Tab Navigation is abit off

### ISSUE THREAD

**Issue by ryoojiz** [SpikeHD/Dorion#24]
![Dorion_xdrSXiAkTr](https://user-images.githubusercontent.com/68143025/235723326-c2388738-2974-4a0e-8819-07409cc96297.gif)

**Comment by SpikeHD** [comment]
Hm, I think that might(?) be an issue with Tauri itself, but I will investigate sometime soon :+1:

**Comment by SpikeHD** [comment]
Nvm, seems to be related to the top bar pushing the site contents down. I'm sure there is a fix but this is not going to be high priority right now :)

**Comment by SpikeHD** [comment]
Though this is closed, the issue wasn't resolved until now: 1c3247d
