### ISSUE TITLE
[Bug] Can't install on Kubuntu 24.04 due to missing dependencies

### ISSUE THREAD

**Issue by yotoprules** [SpikeHD/Dorion#241]
Kubuntu 24.04 cannot install Dorion 5.0.0 or 5.0.1 due to missing dependencies.
The missing package in question (libwebkit2gtk-4.0-37) is not available in the Ubuntu repos, only libwebkit2gtk-4.1-0 is.
So I am unable to install this on my system.
Screenshots below.
Ty!
![Screenshot_20240626_163905](https://github.com/SpikeHD/Dorion/assets/39581623/f2eb1a7f-1db5-4005-8bd8-fe4ef9c6d72a)
![Screenshot_20240626_163843](https://github.com/SpikeHD/Dorion/assets/39581623/8e480f82-00e3-4fef-88d3-fa7c3f6a1a0b)
![Screenshot_20240626_163816](https://github.com/SpikeHD/Dorion/assets/39581623/c61ffcbd-8b24-4d09-992e-2cbaddf44fe4)

**Comment by SpikeHD** [comment]
Doesn't seem like there is a lot I can do without upgrading to the Tauri v2 beta (which would be very involved and might not even work at the moment :P) which uses the newer 4.1 API. You can still download/install the 4.0 version via the older [Ubuntu 22.04 release](https://packages.ubuntu.com/jammy/libwebkit2gtk-4.0-37) of the package, however you prefer to do that :)
