### ISSUE TITLE
[Bug] No audio devices listed

### ISSUE THREAD

**Issue by azazelcodes** [SpikeHD/Dorion#244]
**Describe the bug**
There are only the "Default" option for input and audio device under "Voice & Video" tab. Even with "Default" selected no microphone activity is picked up. Audio outputting works fine.

**To Reproduce**
Issue since install

**Expected behavior**
List of audio devices and working input device.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/68147363/ff000415-ea56-4aac-8d1a-6d64c54688ff)

**System Info (please complete the following information):**
 - OS: Win11
 - Version: v5.0.1

**Comment by azazelcodes** [comment]
Seems to be a system wide problem because Chrome doesn't show devices either. Sorry!

**Comment by SpikeHD** [comment]
A somewhat equivalent option is the "Clear Web-based Data" button found in settings, which resets settings such as microphone/audio devices

**Comment by azazelcodes** [comment]
I've done that but it doesn't fix the devices not showing up.

**Comment by SpikeHD** [comment]
You should be getting permissions popups after you do that, after accessing the Voice and Video settings or a VC, are you getting those/clicking "allow"?

**Comment by azazelcodes** [comment]
Restarting the computer multiple times fixed the issue. Clicking the allow button again after wiping web-based data didn't change anything for me but I had allowed microphone access the first time anyway.
