### ISSUE TITLE
[Feature Request] Multiple Theme Support

### ISSUE THREAD

**Issue by SellyBelly** [SpikeHD/Dorion#248]
I'm used to having Horizontal Server List as well as an actual theme enabled. On Dorian, can only have one theme at once, would be nice to be able to enable two or three like in Vencord.

Only thing I'm missing right now. Testing Dorian as of today, liking it otherwise.

tl;dr: enable multiple theme selection within Dorian rather than a drop down for selecting just one.

**Comment by SpikeHD** [comment]
In the meantime, you can use the [Inline CSS](https://github.com/SpikeHD/shelter-plugins?tab=readme-ov-file#inline-css) shelter plugin, and copy the contents of additional themes you'd like to use (such as [HorizontalServerList](https://discordstyles.github.io/HorizontalServerList/dist/HorizontalServerList.css))

**Comment by SellyBelly** [comment]
Thanks for that! Figured that out about half an hour ago, lol. Does the trick. Appreciate it!

**Comment by SpikeHD** [comment]
This is now implemented as of these changes: https://github.com/spikehd/dorion/compare/250fef9a4456d558cb045c6507e4c2367b9b81d4...80dc486a5341f26ee0d88687e4120abaed31e01e and https://github.com/SpikeHD/shelter-plugins/commit/f5593d72f5c92f2fd1feb475c1f829db515f301b, and will be available in the next release. If you don't want to wait, you can always install and [Actions build](https://github.com/SpikeHD/Dorion/actions/runs/11079725427)!

![multithemedemo](https://github.com/user-attachments/assets/99bb73c5-9d5c-4400-a360-f795972bff78)
