### ISSUE TITLE
Custom images and background are not visible [Bug]

### ISSUE THREAD

**Issue by amethyst-87** [SpikeHD/Dorion#253]
**Describe the bug**
Image does not show up with custom themes. 

**To Reproduce**
Download or make a theme with custom background and icon stuff

**Screenshots**
![Dorion_uTO47bVMth](https://github.com/user-attachments/assets/6ecdeadf-1cb6-48bf-9798-94fc1ab4a718)
![Dorion_SPbD1AEtXv](https://github.com/user-attachments/assets/6aa8c4ba-6f7e-4bdc-988b-79b62a4d5e96)

**System Info (please complete the following information):**
 - OS: Windows 10

**Comment by luximus-hunter** [comment]
External images are not supported in Dorion yet.

**Comment by amethyst-87** [comment]
got it

**Comment by SpikeHD** [comment]
This should be fixed in v6.0.0
