### ISSUE TITLE
[Bug] Can't see person's camera in a call

### ISSUE THREAD

**Issue by Anime-Forevere** [SpikeHD/Dorion#259]
**Describe the bug**
Camera icon doesn't show up & can't be viewed in call.

**To Reproduce**
Get a friend to join voice channel and turn on camera

**Expected behavior**
Camera icon should be visible and you should be able to see person's camera stream

**Screenshots**
On the left is dorion, on the right is vanilla discord
![image](https://github.com/user-attachments/assets/5a3babfb-8fc6-4495-870b-e905cdb9dc4c)

**System Info (please complete the following information):**
 - OS: Windows 10 (22H2, 19045)
 - Version: v6.0.2

**Comment by SpikeHD** [comment]
I can't seem to reproduce (also on Win 10 22H2), are there any error/relevant logs in the DevTools console (Ctrl+Shift+i -> "Console")?

**Comment by SpikeHD** [comment]
I think you win first prize for strangest Dorion bug so far this year. Have you tried disabling Equicord (or even just disabled plugins to see if they are causing it) or openasar (how did you inject that into Dorion in the first place?)? Usually a good first troubleshooting step is to disable stuff until it works again (assuming it does) and keep a note of what was causing it so I can look further

**Comment by Anime-Forevere** [comment]
You were right, it was because of equicord. About openasar, it is injected in normal discord, not Dorion 😅. In Dorion, I use built in theme manager.

**Comment by SpikeHD** [comment]
Thanks for helping get to the bottom of it! If you have the time I'd like to know which specific plugin was causing it, in case it's a Dorion incompatibility and not an Equicord issue, but it's not a huge deal if you don't care enough to figure it out lol

**Comment by Anime-Forevere** [comment]
I found what it was, it was me being an idiot that enabled "Disable cameras in VC" plugin in equicord 😓

**Comment by SpikeHD** [comment]
LOL that would do it, thanks for letting me know!
