### ISSUE TITLE
[Feature Request] Make macOS menubar icon optional

### ISSUE THREAD

**Issue by binford2k** [SpikeHD/Dorion#261]
The macOS menubar icon adds no value for me. I don't want it running, it just takes up space. I should be able to disable it.

**System Info (please complete the following information):**
 - OS: macOS 15.0
 - Version: v6.1.0
 - Extra Client Mods/Plugins: none

**Additional context/Screenshots**

<img width="261" alt="Screenshot 2024-10-02 at 9 43 32 AM" src="https://github.com/user-attachments/assets/359dc2ae-e6b7-4c76-b6af-6cd200266964">

**Comment by SpikeHD** [comment]
This is implemented in 95e571674210f5a91929ed9fea3455a397eeb449 and will be available in the next release

<img width="200" alt="image" src="https://github.com/user-attachments/assets/6524c9cc-7ccd-46a1-a5e6-7797d1133f09">
