### ISSUE TITLE
[Bug][macOS] when minimized, clicking on icon in dock doesnt show window

### ISSUE THREAD

**Issue by Vexcited** [SpikeHD/Dorion#267]
**Describe the bug**

When we close the app while having the "minimize in system tray" option enabled, we can't open the window by clicking on the app in the dock.

**To Reproduce**

- Enable in Dorion Settings "Minimize to System Tray"
- Click the close button on the window so the app is in background
- Click the app icon in the dock
- See it doesn't open

**System Info (please complete the following information):**
 - OS: macOS 15.0.1
 - Version: v6.2.0
 - Extra Client Mods/Plugins: Vencord (also works with none)
 - Any other relevant info: /

**Additional context/Screenshots**
https://github.com/user-attachments/assets/01ed58ee-ebb3-47f6-8d46-4ff6cfa1d163

**Comment by SpikeHD** [comment]
Should be fixed as of 67f9310ab2d4f13688d8250e65abc85cd6f35f1e, and will be available in the next release! If you don't want to wait, you can always download an [Actions build](https://github.com/SpikeHD/Dorion/actions/runs/11502655545)
