### ISSUE TITLE
[Bug] Old version remains in Control Panel after updating

### ISSUE THREAD

**Issue by lettuce8019** [SpikeHD/Dorion#271]
**Describe the bug**
After updating Dorion, the old version remains in Control Panel. The app will be updated however, so I assume this is a purely visual/cosmetic bug. Uninstalling the old version also uninstalls the current build.

**To Reproduce**
1. Start Dorion
2. Get prompt to update within Dorion
3. Update Dorion from within the existing version (not by downloading a new installer from GitHub)

**System Info (please complete the following information):**
 - OS: Windows 10 64-bit (OS Build 19045.5131)
 - Version: Dorion 6.3.0
 - Extra Client Mods/Plugins: [e.g. Vencord with FakeNitro and AlwaysAnimate]
    - Equicord with FakeNitro
 - Any other relevant info:

**Additional context/Screenshots**
![image](https://github.com/user-attachments/assets/d1c0413b-aa69-45f8-9ef0-4b5b6eebb491)

**Comment by SpikeHD** [comment]
Did you by chance install once with the `-setup.exe`, and once with the `.msi` file? You shouldn't mix the two, stick to one or the other (and under almost every circumstance, use the `.msi`). The `-setup.exe` is mostly just for Win 7 users that might have more trouble with the `.msi`

**Comment by SpikeHD** [comment]
Closing because this is entirely cosmetic and I don't really have much control over it anyways
