### ISSUE TITLE
[Feature Request] Remove "Download Apps" button at the bottom of the server list

### ISSUE THREAD

**Issue by CatchFirez** [SpikeHD/Dorion#276]
**Is your feature request related to a problem? Please describe.**

Dorion is better.

**Describe the solution you'd like**

Title

**Describe alternatives you've considered**

N/A

**Additional context**

![image](https://github.com/user-attachments/assets/fddb5810-a64b-4dca-b886-1365bcee22d4)

**Comment by SpikeHD** [comment]
Should be fixed in 6b16b05527911e902ac5d216b933b97cdf453d1b and will be available in the next release
