### ISSUE TITLE
[Bug] Building issue

### ISSUE THREAD

**Issue by MP36ctrl** [SpikeHD/Dorion#279]
**Describe the bug**
_Im trying to build dorion, on **step 7** i get this issue:_
error: failed to run custom build command for `Dorion v6.3.0 (C:\Users\User\Downloads\Compressed\Dorion-6.3.0 source\Dorion-6.3.0\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\Users\User\Downloads\Compressed\Dorion-6.3.0 source\Dorion-6.3.0\src-tauri\target\release\build\Dorion-cc35168ee837792b\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=dorion
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=com_spikehd
  cargo:rustc-check-cfg=cfg(dev)
  cargo:PERMISSION_FILES_PATH=C:\Users\User\Downloads\Compressed\Dorion-6.3.0 source\Dorion-6.3.0\src-tauri\target\release\build\Dorion-04e1aadd19d90035\out\app-manifest\__app__-permission-files
  cargo:rerun-if-changed=capabilities
  cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=x86_64-pc-windows-msvc
  cargo:rerun-if-changed=injection\shelter.js
  cargo:rerun-if-changed=icons\icon.ico
  cargo:rerun-if-changed=extension\dnr-rules.json
  cargo:rerun-if-changed=extension\manifest.json
  glob pattern updater* path not found or didn't match any files.
warning: build failed, waiting for other jobs to finish...
failed to build app: failed to build app
    Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.
**To Reproduce**
Follow instructions to step7
**System Info (please complete the following information):**
 - OS: Windows 10
 - Version:  v6.3.0
 
I was also getting this error before if this is anything related:

    Finished `release` profile [optimized] target(s) in 39.88s
'cp' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by SpikeHD** [comment]
Ah right, the `build:updater` command, which is run as part of the build process, runs the `cp` command which is only available when using Git Bash (or msys2 or whatever). So, when the updater fails to move to the new location, the next build step tries to find it and cannot.

Try running the build commands in [git bash](https://git-scm.com/downloads) if you don't have it installed already.

**Comment by MP36ctrl** [comment]
seems to be stuck here now:
![image](https://github.com/user-attachments/assets/df61e569-f465-4eef-9587-d2590c119417)

**Comment by MP36ctrl** [comment]
Gitbash worked, tyy
