### ISSUE TITLE
Add option to change mic input

### ISSUE THREAD

**Issue by ryoojiz** [SpikeHD/Dorion#28]
Since Dorion is (obviously) based off the web-app, you can't really change the Input device for Voice. I believe the way to do this is on webview is to prompt user for microphone permissions (?), then you could change the input device in the permissions box (default behaviour on chromium atleast)

**Comment by cyberhardt** [comment]
I seem able to do that just fine, in fact, there are more mic options on Dorion than on regular discord for some reason

**Comment by SpikeHD** [comment]
I too am not missing these options, @ryoojiz what sort of system are you on? You can close and remake this issue if you'd like to use the issue templates as well 👍

**Comment by ryoojiz** [comment]
I am using Windows 10 and installed with the precompiled installer, for some weird reason the input and output selection now show all the peripherals! Guess this can be closed now lol.
