### ISSUE TITLE
[Bug] Multiple Critical Errors

### ISSUE THREAD

**Issue by FreshSoftware4** [SpikeHD/Dorion#281]

**Comment by SpikeHD** [comment]
Sending the logs directly would be infinitely more useful than ChatGPT's contextless guessing 😄. Also, please describe the bug with real detail as "errors in initializing plugins" tells me very little.

Also, do not add any `dorion-xyz` plugins manually, they are already injected internally and having them inject more than once will for sure cause them to clash. That is likely most of what your are experiencing.
