### ISSUE TITLE
[Bug] Missing package preventing Dorion from launching

### ISSUE THREAD

**Issue by Animationss** [SpikeHD/Dorion#282]
**Describe the bug**
webkit2gtk-4.1 package not installed when installing dorion. 

**To Reproduce**
Ran `yay -S dorion-bin`
Not completely sure, may have been an isolated issue with my arch install. 

**System Info**
 - OS: Arch 
 - Version: 6.12.7-arch1-1

**Additional context/Screenshots**
[Video](https://upload.animationsz.lol/u/LTl0Cv.mp4)

**Comment by SpikeHD** [comment]
You will have to leave a comment on the [`dorion-bin` AUR page](https://aur.archlinux.org/packages/dorion-bin) (perhaps linking this issue in it would help too), I don't maintain the Arch package so I can't really help haha
