### ISSUE TITLE
Ability to drag files to the client to send

### ISSUE THREAD

**Issue by Liz-chan** [SpikeHD/Dorion#3]
Currently, if you try to drag a photo or a file into the client to send it, nothing happens while you're dragging it or after you drop it. In the stock client and the website, you can send files by dragging it into the window, so I think it'd be a good improvement to have this in Dorion as well.

**Comment by SpikeHD** [comment]
Seems like Tauri doesn't support [dragging and dropping](https://github.com/tauri-apps/tauri/discussions/4736) the way native web does, so I'll have to come up with a work around.

**Comment by Liz-chan** [comment]
I also wanted to mention that dragging servers into folders doesn't work either, so that might be related as well.

**Comment by SpikeHD** [comment]
30d090a should fix both this, and #32
