### ISSUE TITLE
[BUG] Linux: "Unsupported Browser" when trying to join a voice

### ISSUE THREAD

**Issue by user8295** [SpikeHD/Dorion#30]
Can't join a voice, can't unmute, because Discord detects browser as unsupported.

When trying to unmute, Discord prompts with the "Unsupported Browser" "Use latest version of Chrome/ Firefox" etc.

I'm using the AUR build (0.5.0-1) on Manjaro + Wayland.

No idea what other info to attach...

**Comment by SpikeHD** [comment]
Oh! Someone put it on the AUR, that's cool, thank you "Refined7075" :P

I did a lot of reading into why this would be happening, and it unfortunately boils down to the fact that the version of `Webkit2GTK`, the backend used in the Linux version, used by Tauri does not yet support WebRTC. It is apparently [hidden behind a build-time flag](https://github.com/tauri-apps/wry/issues/85#issuecomment-1510488196) and therefore not easily accessible by me OR them until the feature is stable.

There is *essentially* nothing I can do about this at the moment. While I would *love* for the releases to compile Webkit2GTK from source with the flag, I don't know how - if possible - I would coax Tauri into doing that.

Maybe there are alternative releases that contain the flag out there somewhere, but I wouldn't know where to look. I would consider writing a slightly modified version of Tauri to install/use an alternative, WebRTC-enabled build if something like that DOES exist, though!

**Comment by SpikeHD** [comment]
Nope! But I would be happy to accept a PR from whoever put it up there, or I will just throw a PKGBUILD in here sometime soon.

**Comment by SpikeHD** [comment]
The new Webkit2GTK update recently fixed injection AND voice support! Linux builds are no longer the runts of the litter.

**Comment by Daktyl198** [comment]
I am once again receiving this error, using the latest version of Dorion on Arch Linux.
