### ISSUE TITLE
drag and drop servers

### ISSUE THREAD

**Issue by cyberhardt** [SpikeHD/Dorion#32]
**Is your feature request related to a problem? Please describe.**
You can't drag and drop servers to remove them from folders, nor can you create new folders for servers

**Describe the solution you'd like**
Make it so that you are able to do it

**Describe alternatives you've considered**
An alternative would be to enable the creation and management of server folders with the right click or something of the sort

**Additional context**
Windows 10 22H2 last Dorion version

**Comment by cyberhardt** [comment]
related: https://github.com/SpikeHD/Dorion/issues/3

**Comment by SpikeHD** [comment]
Should be fixed in 30d090a
