### ISSUE TITLE
minimize to tray + hide/show functions on tray icon

### ISSUE THREAD

**Issue by cyberhardt** [SpikeHD/Dorion#33]
**Is your feature request related to a problem? Please describe.**
Would be nice to enable Minimize to Tray function and also make it possible to click on the tray icon to hide/show the client.

**Describe the solution you'd like**
Create an option to enable Minimize to Tray and enhance the tray icon by making it so that you can hide/show the client by left-clicking on it, and/or by right-clicking on it

**Describe alternatives you've considered**
-

**Additional context**
Windows 10 22H2 on latest Dorion version

**Comment by SpikeHD** [comment]
This mostly works! Check `Dorion Settings` to enable it (it will work when using "X" to close the window). Left click to open the window or right click the tray icon to view options there :)

![image](https://github.com/SpikeHD/Dorion/assets/25207995/69bef0a9-4732-4ccd-9e69-868e320d9fdc)

![image](https://github.com/SpikeHD/Dorion/assets/25207995/d7fd3490-1724-4e66-965c-211519f4ef22)
