### ISSUE TITLE
Can't use plugins.

### ISSUE THREAD

**Issue by Voidzex** [SpikeHD/Dorion#36]
When i put plugins in the plugins folder it shows at the place where can i enable plugins, but when i click ''Enabled?'' or ''Preload?'' buttons it doesn't enable the plugin.
![image](https://github.com/SpikeHD/Dorion/assets/135425000/09635bc5-1fb3-4424-9a54-081b328bf204)
![image](https://github.com/SpikeHD/Dorion/assets/135425000/a5d9b457-a6e4-4b09-b607-4e90389fd49b)

My system is :
 - Windows 8.1

**Comment by SpikeHD** [comment]
Are these BetterDiscord plugins? Dorion doesn’t support those, only browser-based ones.

**Comment by SpikeHD** [comment]
(You might be able to preload BdBrowser and they may work then, but I’ve never tried it https://github.com/tsukasa/BdBrowser)

**Comment by ryoojiz** [comment]
Could you explain where I could source vencord plugins? I tried to install FakeNitro directly from Vencord's github but it doesn't work.

**Comment by SpikeHD** [comment]
@ryoojiz Grab their [browser.js](https://github.com/Vendicated/Vencord/releases/download/devbuild/browser.js) (and the CSS too probably, you can set it as a theme if the Vencord CSS is brokey), and set that browser.js file as its own plugin. Then enable whatever Vencord plugin you want from their plugins page.

**Comment by ryoojiz** [comment]
Opening the settings with browser.js auto enabled will crash discord, I can't disable browser.js unless I remove the file

**Comment by BlueKeyMS** [comment]
> Opening the settings with browser.js auto enabled will crash discord, I can't disable browser.js unless I remove the file

Rename browser.js to PRELOAD_Vencord.js and enable plugin in settings

**Comment by SpikeHD** [comment]
With the new release, Vencord is included by default, so issues regarding it should be resolved (make sure to remove your own Vencord install! :P)
