### ISSUE TITLE
[Feature Request] Noise Supression

### ISSUE THREAD

**Issue by notoriouslyaidiot** [SpikeHD/Dorion#38]
**Describe the bug**
Noise suppression doesnt work as well on dorain vs normal discord
**To Reproduce**
Steps to reproduce the behavior: Use discord on a alt on your phone and on your pc and do something like snapping while talking, etc and its more likely to go through on dorian. you could also use 2 discord accounts one on dorian one on the normal discord (not tested), or get friends and test it on dorian vs normal discord and tell them to tell you which one they can hear or sounds louder.

**Expected behavior**
Describe what should be expected here. sound suppression to work

**Screenshots**

**System Info (please complete the following information):**
 - OS: [e.g. Windows 11, Ubuntu 22.04] Windows 10
 - Version: [e.g. v0.5.0] 0.5.0
 - Any other relevant info: 

**Additional context**
Add any other context about the problem here. Sorry if the bug report is a vague

**Comment by Small-Ku** [comment]
I think this is a feature request since we don't have a way to get Krisp work in Dorion
https://support.discord.com/hc/en-us/articles/360040843952

**Comment by Small-Ku** [comment]
Related: https://github.com/Vendicated/Vencord/pull/1477

**Comment by Vendicated** [comment]
This is now a plugin part of Vencord. Assuming dorion supports wasm, it should just work (though you'll of course have to update your fork first)

**Comment by SpikeHD** [comment]
Thanks for letting me know!

Currently giving me an "Abort error" when enabling, but I'm sure it's some quirk with Dorion, so I'll see about attempting to investigate and fix sometime soon 👍

**Comment by SpikeHD** [comment]
While RNNoise still doesn't work on Dorion (from what I can tell), Krisp is seemingly available, so I'll close this for now.
