### ISSUE TITLE
[Feature Request] Custom keybinds

### ISSUE THREAD

**Issue by thefatos** [SpikeHD/Dorion#39]
The title is self-explanatory but in the keybinds settings it shows to download the app for custom keybinds.

**To Reproduce**
Open the Keybinds section in Discord Settings.

**Expected behavior**
It should show as the normal Discord app and custom keybinds should work.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/94957716/1c9098a9-d700-447d-b7ce-f77b8d387a8b)

**System Info (please complete the following information):**
 - OS: [Windows 10, build 19045.2965]
 - Version: [v0.5.0]

**Comment by SpikeHD** [comment]
With the release of v0.6.0, it might be possible for me to now implement custom keybinds, but I have yet to look and will update if I find anything

**Comment by andriejs** [comment]
@SpikeHD This can possibly be done by using the injection script to make the (web keybind banner) disappear and make them editable. and using rust on the backend you can make them global.

**Comment by SpikeHD** [comment]
Yep that was basically the idea. Hoping I can just enable all of the functionality in the frontend easily and just hook into wherever it tries to actually watch for the keybinds, but we shall see

**Comment by andriejs** [comment]
mhm

**Comment by EinsKatze** [comment]
Looking forward to this, cuz as of now, no custom client seems to have Global Custom Keybinds

**Comment by SpikeHD** [comment]
This is on the way via [shelter-plugins#29](https://github.com/SpikeHD/shelter-plugins/pull/29), I also posted this demo in the Discord a little while ago:


https://github.com/SpikeHD/Dorion/assets/25207995/b9e2be7a-a76e-4c4a-8916-844bc9c9da80

It's basically fully custom functionality on both the frontend AND backend, so it'll be a little while still, but it *is* being worked on

**Comment by EinsKatze** [comment]
> This is on the way via [shelter-plugins#29](https://github.com/SpikeHD/shelter-plugins/pull/29), I also posted this demo in the Discord a little while ago:
> 2024-06-17_21-49-07.mp4
> 
> It's basically fully custom functionality on both the frontend AND backend, so it'll be a little while still, but it _is_ being worked on

Video looks good, keep up the great work.

**Comment by SpikeHD** [comment]
After 380 days / 12.5 months / 27.14 Fortnights, custom keybinds is now an officially supported part of Dorion as of [v5](https://github.com/SpikeHD/Dorion/releases/tag/v5.0.1)!
