### ISSUE TITLE
Activities in Voice Calls pushed down due to Custom Topbar[BUG]

### ISSUE THREAD

**Issue by ryoojiz** [SpikeHD/Dorion#40]
**Describe the bug**
As described and seen in the screenshot, whatever activity is showing when you're fullscreen in a voice call will be pushed down by a few pixels obstructing some view of the member list, as spike had noted a similar tab selection issue occuring due to the custom topbar, then I will assume the same too.

**To Reproduce**
Just enter any voice call and start an activity, it might work best with interactive game style activities.

**Expected behavior**
Activity window centered in it's div.

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/68143025/cd10aeb8-3d83-402a-b749-e6805b954cb2)

**System Info:**
 - OS: Windows 10 22H2
 - Version: v0.5.0
 - Any other relevant info: No plugins enabled, only a [theme](https://catppuccin.github.io/discord/dist/catppuccin-mocha.theme.css)

**Comment by ryoojiz** [comment]
+Dorion likes to create multiple instances of itself, sometimes up to 10 and cloning the Dorion Settings button then proceeds to crash after 3-5 seconds??? I have no idea
![Screenshot](https://cdn.upload.systems/uploads/Z3pDJ9TH.png)

**Comment by SpikeHD** [comment]
Fixed in 1c3247d
