### ISSUE TITLE
Not actually portable? [BUG]

### ISSUE THREAD

**Issue by Mason-17** [SpikeHD/Dorion#41]
**Describe the bug**
The portable version of the app (```Dorion_Win64_Portable.zip```) create folders outside of the main directory, namely in APPDATA and the user's home directory on windows (for plugins/themes)

**To Reproduce**
Use portable version

**Expected behavior**
Files and folders should be created in the portable app's directory.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
You're definitely right, I haven't put much thought into the "portable" versions up until recently. I will put some work into making them *actually* portable, but for now they will be called "SemiPortable" :P

**Comment by Mason-17** [comment]
> You're definitely right, I haven't put much thought into the "portable" versions up until recently. I will put some work into making them *actually* portable, but for now they will be called "SemiPortable" :P

Sounds good, lol. Question: since the folders created seem to only be for theming and plugins, is it a possibility to be able to put a relative path instead for the installation folder? As a temporary workaround?

**Comment by SpikeHD** [comment]
Very weird... I wonder if it's a problem with Webview and it's interactions with mobile GPUs or something. I'll do some investigation but I don't have a working Windows laptop right now, so that may be a ways away.

**Comment by SpikeHD** [comment]
It won't recognize relative paths right now, but I don't see it being a breaking change to just check for relative theme/plugin paths and use those they exist, and if they aren't found it would use the regular `%appdata%` route. I'll try to remember to include that in the next release

**Comment by SpikeHD** [comment]
`v0.6.2` now has portability detection. Note that if any of `config.json`, `plugins/` or `themes/` do not exist beside the executable, it will attempt to create the respective directory/file the normal way, so make sure they're there. When updating portable releases, though, don't accidentally overwrite your config :P
