### ISSUE TITLE
Not working on macOS normally

### ISSUE THREAD

**Issue by z3ven** [SpikeHD/Dorion#44]
**Describe the bug**
First, there was a problem with the building. I could only build the dev version. When I opened Dorion on my Mac, login animation was laggy. Then when I wanted to join the voice channel, it wrote: "Your browser is deprecated". 

**To Reproduce**
Open Dorion. You will see laggy login animation
Join a voice channel or undeafen yourself

**Expected behaviour**
feels really laggy

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-08 at 10 05 09" src="https://github.com/SpikeHD/Dorion/assets/91781891/6885df26-6dcb-486d-b939-8915db595a95">

<img width="1440" alt="Screenshot 2023-07-08 at 10 05 14" src="https://github.com/SpikeHD/Dorion/assets/91781891/02012f02-0e6b-4f39-b201-17dfb293ef79">

**System Info (please complete the following information):**
 - OS: macOS 13.4.1
 - Version v0.5.0
 - Any other relevant info: M1 MacBook Air
**Additional context**
maybe the problem with WebKit

**Comment by SpikeHD** [comment]
I only just bought an M1 Macbook a couple weeks ago, so unfortunately Mac builds have gone 100% untested as of now. Will look into it eventually 👍.

**Comment by SpikeHD** [comment]
@z3ven I rebuilt a release build on my 2020 M1 Macbook Pro and it ran perfectly fine. Voice channel joining doesn't seem to work because the MacOS WKWebview probably doesn't support WebRTC, like on Linux (#30). Could probably implement it [with this](https://github.com/tmthecoder/WebRTC-macOS), which is something I have never done before, and would almost definitely require forking Tauri/Tao, so unfortunately its not a terribly huge priority.

Can you paste the problems/errors you got while attempting to build a release version?

**Comment by z3ven** [comment]
* First, I ran `cargo install` to install all the dependencies (All commands I took from the README.md file in the repository). However, I encountered an error:
`Using `cargo install` to install the binaries for the package in the current working directory is no longer supported. Please use `cargo install --path .` instead. If you only want to build the package, use `cargo build`.`
* Second, I used `npm tauri build` to build the Tauri app, but I encountered the following error:
`Error: beforeBuildCommand 'yarn build' failed with exit code 127.
`

**Comment by SpikeHD** [comment]
1. Try following what the error told you and run `cargo install --path .`, assuming you are already navigated into the `src-tauri` folder like the README mentions.
2. Looks like I forgot to make the scripts npm-friendly haha. Use `yarn` for now, or look in `package..json` and run the commands for building manually

**Comment by z3ven** [comment]
Tried using `cargo install --path`, not working. Will try installing yarn

**Comment by SpikeHD** [comment]
I have a feeling you forgot the `.` at the end of the cargo command, but you can also try `cargo build`. It's possible that running `yarn tauri build` without running anything cargo-related will still work, but I don't know off the top of my head.

**Comment by z3ven** [comment]
thx! Helped
