### ISSUE TITLE
[BUG] Plugins with dynamically imported module not working

### ISSUE THREAD

**Issue by Small-Ku** [SpikeHD/Dorion#47]
**Describe the bug**
Using petpet plugin and it shows this error:
```
TypeError: Failed to fetch dynamically imported module: https://unpkg.com/gifenc@1.0.3/dist/gifenc.esm.js
```

**To Reproduce**
1. Enable the plugin, petpet
2. Try to petpet from chat

**Expected behavior**
GIF is successfully made and ready for sending.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11 23H2 25905.1000
 - Version: v0.6.2
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
The way Vencord disables CSP is either through a browser extension method (not available to Dorion, WebViews don't support extensions) or through methods only available in the client modification version (also obviously not available to Dorion).

It's been talked about in the [Tauri discussions](https://github.com/tauri-apps/tauri/discussions/3463) and the short answer to that, too, is that it's not possible. I will see if I can modify my forked version to load libraries in the backend though.

**Comment by mollthecoder** [comment]
> The way Vencord disables CSP is either through a browser extension method (not available to Dorion, WebViews don't support extensions) or through methods only available in the client modification version (also obviously not available to Dorion).
> 
> It's been talked about in the [Tauri discussions](https://github.com/tauri-apps/tauri/discussions/3463) and the short answer to that, too, is that it's not possible. I will see if I can modify my forked version to load libraries in the backend though.

I don't know much about Tauri, but I did a search and stumbed upon [this.](https://github.com/tauri-apps/tauri/issues/3583#issuecomment-1114385570)
