### ISSUE TITLE
[BUG] Bad folder open in Dorion Settings

### ISSUE THREAD

**Issue by Dysta** [SpikeHD/Dorion#48]
**Describe the bug**
In Dorion Settings menu, when clicking on the Folder Icon to open the Plugins Folder, it open the Theme Folder

**To Reproduce**
Go to settings > Dorion Settings then click on the folder icon related to Plugins Folder

**Expected behavior**
Open the correct folder

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/25008828/84cf2532-8746-4452-9298-eb18ec12f836)

**System Info (please complete the following information):**
 - OS: [e.g. Windows 10 64b]
 - Version: 0.6.2
 - Any other relevant info: Chromium 144

**Additional context**

**Comment by Dysta** [comment]
Btw the big folder icons was a weird bug that solve when I restarted the client

**Comment by Small-Ku** [comment]
It seems not loading custom CSS in every first start after turning on PC

**Comment by Small-Ku** [comment]
I mean custom CSS from Vencord. You should also see these I think:
![圖片](https://github.com/SpikeHD/Dorion/assets/16464896/818d41cf-a5b9-41fe-8cc4-6ae4779db066)
![圖片](https://github.com/SpikeHD/Dorion/assets/16464896/4a1aff1c-d3c4-4705-ab7c-0be310560413)

**Comment by Dysta** [comment]
at first launch yes, after a reboot it's display like it should :)
btw it not the topic of this issue

**Comment by SpikeHD** [comment]
Fixed and will be available in next release 👍
