### ISSUE TITLE
[BUG] Portable remembering/caching info

### ISSUE THREAD

**Issue by Mason-17** [SpikeHD/Dorion#49]
**Describe the bug**
The portable app after upgrading remembers my login info.

**To Reproduce**
1. Use old portable version 
2. Update and delete old portable folder 
3. Use new portable version. It doesn't ask for login info.

**Expected behavior**
The portable app shouldn't remember the previous version's credentials 

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: Latest
 - Any other relevant info: 

**Additional context**

**Comment by Mason-17** [comment]
> While I have no direct control over where the cache goes, as far as I'm aware, I am planning to add [manual, full cache clearing](https://github.com/SpikeHD/Dorion/blob/09d242dd7ce65e5d723ebd4af822fbe655f4ceae/src-tauri/src/helpers.rs#L79) capabilities, so you'll be able to use that when it's ready for all platforms.

Does this mean I'll be able to clear the cache before moving my install to another device via usb?

**Comment by SpikeHD** [comment]
In theory your cache shouldn’t persist across PCs, just throughout the same PC

**Comment by Mason-17** [comment]
> In theory your cache shouldn’t persist across PCs, just throughout the same PC

Right, but it would be ideal if the app cached everything within its own folder. It's a shame you can't control the cache location.

**Comment by SpikeHD** [comment]
I have implemented a custom web cache directory in 6a10e3d49b4ee6c22e70cf5fc56122d841e808d2. This now means you can clear the cache with ease on regular AND portable installs.

Regular installs have it located in `%appdata%/dorion/webcache` and portable installs have it located in `your_dorion_folder/webcache`. This also means deleting a portable Dorion install takes the cache with it!
