### ISSUE TITLE
[BUG] Discord components links don't open

### ISSUE THREAD

**Issue by Dysta** [SpikeHD/Dorion#50]
**Describe the bug**
When you click on a discord button components that redirect to a link, the link don't open and nothing happen.

**To Reproduce**
Have a message with button components attached to it and click one of the buttons.

**Expected behavior**
The redirect link should open in a browser or something

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/25008828/0a208c92-9e74-476b-b9cf-0f0adfcdf777) then click into one button and nothing happen

**System Info (please complete the following information):**
 - OS: MacOS Ventura 13.4.1, M2 
 - Version: 0.6.2
 - Any other relevant info: Bot used on the screenshot => https://dysta.github.io/JukeBotLab/ with command **/link**

**Additional context**
Same error with link in the **about me** section 
![image](https://github.com/SpikeHD/Dorion/assets/25008828/815b4eab-e95d-4bcd-9893-211ef81cee9c)
Tested with and without the vencord plugin **OpenInApp** and the bug is still here

**Comment by Dysta** [comment]
Tested with my windows 10 and the issue is different, url and buttons open a weird explorer screen instead of using the default browser
![image](https://github.com/SpikeHD/Dorion/assets/25008828/94fbd78a-d0b0-4a54-8796-7504870a3786)

**Comment by SpikeHD** [comment]
Will probably require implementing the same changes as #2 which I was planning to tackle sometime soon

**Comment by Dysta** [comment]
Yup, link in chat and markdown link like this 
![image](https://github.com/SpikeHD/Dorion/assets/25008828/6fb4ffdd-fb1f-4c98-9071-f54d55d0a806)
work correctly,

**Comment by Dysta** [comment]
Hello, I would like to add that I discover a new components that doesn't open link. When a pinned message contain a like, we can directly click on the link and open it. We need to click on the jump button then click on the link in the message.
Version : latest (0.7.2), OS: MacOS Ventura

![image](https://github.com/SpikeHD/Dorion/assets/25008828/4e940cca-73fa-4638-bb5f-c26299c64ceb)

**Comment by SpikeHD** [comment]
Component links fixed in https://github.com/SpikeHD/Vencordorion/commit/3acf808537510e361c053cb7c6cf0c1e66ec4e49
Pinned message/search results/etc. still WIP

**Comment by SpikeHD** [comment]
Should be fixed in 4c44d8d and will be available in the next release!
