### ISSUE TITLE
[Feature Request] Real-time css editor

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#53]
I would like to see a real-time CSS editor like the one found in BetterDiscord
If that turns out to be hard, at least having a non real-time CSS editor would be better than having nothing.

Here is the editor in BD for context:
![css-editor](https://github.com/SpikeHD/Dorion/assets/91745601/cfc888c5-5c65-4124-bbf4-a8e6d0f21574)

**Comment by SpikeHD** [comment]
Only took half a year, but you can now use the "Inline CSS" plugin from my [shelter-plugins repo](https://github.com/SpikeHD/shelter-plugins)
