### ISSUE TITLE
[Bug] The client doesn't start after installing on windows 10 via the msi installer

### ISSUE THREAD

**Issue by Koulmoir** [SpikeHD/Dorion#54]
**Describe the bug**
doesn't start

**To Reproduce**

**Expected behavior**
Describe what should be expected here.

**Screenshots**

**System Info (please complete the following information):**
 - OS: windows 10
 - Version: v0.7.3
 - Any other relevant info: I was using the msi installer

**Additional context**
I also tried reinstalling but that still doesn't fix it

**Comment by SpikeHD** [comment]
Can you try v0.7.2? Newest version has been having trouble on my Macbook and I'm wondering if that problem is persisting to new installs on other platforms as well

**Comment by Koulmoir** [comment]
nope tried v0.7.2 also just opens the window briefly

**Comment by SpikeHD** [comment]
Try going through all of the [troubleshooting steps](https://github.com/SpikeHD/Dorion#troubleshooting), I just updated them.

**Comment by Koulmoir** [comment]
Took a long time to figure out how to actually reinstall it (cause windows 10) but by installing edge uninstalling it with the full package (the removeedge.exe) and then just installing it worked thx
