### ISSUE TITLE
[Feature Request] Add native window style

### ISSUE THREAD

**Issue by xemulat** [SpikeHD/Dorion#55]
**Is your feature request related to a problem? Please describe.**
Unable to use native window style.

**Describe the solution you'd like**
Allow the use of the native window style, like in ArmCord:

![image](https://github.com/SpikeHD/Dorion/assets/98595166/86e4b19e-5b60-42b0-b9f4-093e6592bb53)

**Describe alternatives you've considered**
No alternatives available.

**Additional context**
Screenshot provided above.

**Comment by SpikeHD** [comment]
What platform are you on? Windows (and I think Linux?) already have this

**Comment by SpikeHD** [comment]
Added in 4429ca94ae0384ce2c3d8210a817a54b935c7d8a and will be available in the next release
