### ISSUE TITLE
[Feature Request] Vencord on Linux

### ISSUE THREAD

**Issue by Vap0r1ze** [SpikeHD/Dorion#57]
you use your own builds of Vencord now, you could transform regex to custom constructors in the build script using smth like [acorn](https://www.npmjs.com/package/acorn) on the final `renderer.js` file

>`/(?<=joe)/i` -> `new CustomRegExp('(?<=joe)', 'i')`
>`new RegExp('(?<=joe)', 'i')` -> `new CustomRegExp('(?<=joe)', 'i')`

and then proxy match/exec calls like this
```ts
window.CustomRegExp = SUPPORTS_LOOKAROUND ? RegExp : class CustomRegExp implements RegExp {
    constructor(public source: string, public flags = '') {}
    [Symbol.match](text) {
        tauriIpc.doMatch([this.source, this.flags], text)
    }
    // other methods
}
```
and then use some rust regex engine for it. could probably do optimizations that make the performance hit minimal too tbh

**Comment by SpikeHD** [comment]
I knew I could do the regex with Rust but I couldn't really come up with a good way to do it. This looks super solid theoretically, I'll do some experimentation!

**Comment by Vap0r1ze** [comment]
someone in the vencord server just showed me it working on their linux, maybe its fixed in a new release (WebKit/WebKit#7109?)

**Comment by SpikeHD** [comment]
Probably works in normal browsers but Webkit2GTK loves being silly and different (and behind), so they lack a lot of features that upstream WebKit has (such as WebRTC, it's apparently working, but locked behind a build-time flag and not available in any release).

**Comment by Vap0r1ze** [comment]
no i meant dorion

**Comment by SpikeHD** [comment]
?? wait really ?? I've tested Dorion a bunch on Linux and it's never properly worked for me due to invalid RegEx...

...am I just using a bunk-ass version of Kubuntu 22.04 or something?

**Comment by SpikeHD** [comment]
What Linux are they running?

**Comment by Vap0r1ze** [comment]
lol idk i would show u but ur not there

**Comment by SpikeHD** [comment]
Meant to close this since I tested it myself and it's now working :muscle:
