### ISSUE TITLE
[Bug] Double app title bar appears in linux (arch + KDE)

### ISSUE THREAD

**Issue by duch3201** [SpikeHD/Dorion#58]
**Describe the bug**
like i said in the title, on top of the title bar provided by Dorion the native one from KDE also appears
im gonna poke around in the code, i might find a fix though i don't have a lot of experience with Rust

**To Reproduce**
i compiled it from source, and i saw the double title bar

**Expected behavior**
well, only one title bar should appear, either the native OS one, or the Dorion one

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/56601374/bd319394-7207-4b53-8cae-a6841a231a40)

**System Info (please complete the following information):**
 - OS: Arch Linux 
 - Version: 6.4.8-zen1-1-zen
 - Any other relevant info: None

**Additional context**
None

**Comment by SpikeHD** [comment]
Are you on X11 or Wayland? Maybe one of the two doesn't like working properly

**Comment by duch3201** [comment]
> Are you on X11 or Wayland? Maybe one of the two doesn't like working properly

im on wayland, and i haven't tested it on X11 yet, i am planning on doing that though

**Comment by SpikeHD** [comment]
I'm willing to bet it's just Wayland being Wayland, lemme know what you find 👍
