### ISSUE TITLE
[Bug]push to talk not working

### ISSUE THREAD

**Issue by Koulmoir** [SpikeHD/Dorion#59]
just straight up doesn't work

**Comment by SpikeHD** [comment]
What key combo are you using? OS? Please use the issues templates

**Comment by Koulmoir** [comment]
I'm using windows 10 and ctrl + B

**Comment by Koulmoir** [comment]
Also it pops up as a green dot around my pfp indicating I'm talking and in mic test it works but for the other people i'm not talking / producing sound

**Comment by SpikeHD** [comment]
Interestingly, it works totally fine for me (Win 10, used your keybind). I assume having it set to voice activity works fine? I also assume DorionPTT is enabled (as it should be default) in Vencords "plugin" section?

![image](https://github.com/SpikeHD/Dorion/assets/25207995/af07284c-7d86-43bc-aa50-2ebebf362aac)

**Comment by SpikeHD** [comment]
Closing in favor of the better duplicate #80
