### ISSUE TITLE
is there ever going to be better discord plugin support and also is there openasar support or no

### ISSUE THREAD

**Issue by Pickymarker** [SpikeHD/Dorion#6]
is there ever going to be better discord plugin support and also is there openasar support or no

**Comment by SpikeHD** [comment]
No. BetterDiscord plugins require the NodeJS runtime (which comes with Discord, but is also the reason it is so bloated). Bundling the NodeJS runtime into Dorion would make it redundant lol.

Depending on the plugin, it could probably be translated into a Dorion-supported plugin manually, but that would require some amount of effort.
