### ISSUE TITLE
[Bug] Crash on startup with MacOS

### ISSUE THREAD

**Issue by Dysta** [SpikeHD/Dorion#60]
**Describe the bug**
Since the version 0.7.2, Dorion crash on startup. Tested with version 0.8.0 and the problem is still here

**To Reproduce**
Use MacOS Ventura, update Dorion to a version >= 0.7.2 and launch Dorion.

**Expected behavior**
Dorion start correctly

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/25008828/2e38ea19-6008-494e-a984-d074e859a841)

**System Info (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - Version: >= 0.7.2
 - Any other relevant info: 
 Macbook M2

**Additional context**
Dump of the crash from MacOS:
https://gist.github.com/Dysta/92c857d43c7c642aa5b308f698ba2e4c

**Comment by psharma04** [comment]
Currently works through Rosetta if you need a quick fix (Dorian 0.8.0, MacOS 14.0, Sonoma 23A5286g, M1 MacBookAir10,1).

**Comment by SpikeHD** [comment]
Okay, having the same problem on my M1, will investigate soon 👍

**Comment by SpikeHD** [comment]
Aha! It's a problem with the `device_query` crate. Don't know why it's only started to act up now, but I'm just going to disable that functionality for now since MacOS doesn't even use it yet. 

You can download a new `.dmg` from the same v0.8.0 release page, it's been updated to have the fix :)

**Comment by Dysta** [comment]
The latest update seem to fix the crash but the installer have a weird behavior.
Here is a pic of it, we can't put Dorion in the Applications
![image](https://github.com/SpikeHD/Dorion/assets/25008828/176c413b-fa1b-442d-af38-7e964bb8ff24)

**Comment by SpikeHD** [comment]
Yea idk what up with that, might just be a fluke, just open Finder and drag it into “Applications” that way
