### ISSUE TITLE
[Bug] Can't zoom

### ISSUE THREAD

**Issue by electricsteve** [SpikeHD/Dorion#61]
**Describe the bug**
You can't change the scale of chats and all ui, like in the desktop app and website.

**To Reproduce**
Always

**Expected behavior**
Be able to change the scale of the ui.

**Screenshots**
Fully zoomed in on normal discord:
![image](https://github.com/SpikeHD/Dorion/assets/96793824/9bce46a0-6a86-407b-8ec9-148cf3c3c043)
Fully zoomed out on normal discord:
![image](https://github.com/SpikeHD/Dorion/assets/96793824/7564e3b4-3b30-46ba-8ee0-9d049afe2960)
Only level of zoom dorion can be on:
![image](https://github.com/SpikeHD/Dorion/assets/96793824/ad87ad5a-7c4d-4c48-b8b7-179011eef425)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v0.7.3
 - Any other relevant info: -

**Additional context**
-

**Comment by SpikeHD** [comment]
Closing unless for some reason that slider doesn't work for you

**Comment by electricsteve** [comment]
It does work, but when saved and restarted, it is at the zoom level, but the slider says it is always at 50% while it isnt

**Comment by SpikeHD** [comment]
Move to v0.7.4 or higher, that is a bug that has been fixed 👍
