### ISSUE TITLE
[Bug] Message link handling

### ISSUE THREAD

**Issue by LavellanDWR** [SpikeHD/Dorion#63]
**Describe the bug**
Message links (such as "Jump to message" with the Starboard bot) open in the default browser instead of the app.

**To Reproduce**
Click on message link.

**Expected behavior**
Jumping to the message in the server (switching to the correct channel, finding the message, autoscrolling to it, highlighting it briefly).

**System Info:**
 - OS: Windows 10
 - Version: 0.8.0
 - .msi install

**Comment by SpikeHD** [comment]
Fixed in: https://github.com/SpikeHD/Vencordorion/commit/e720f0a322f0eeecf415214530d6d8ad5e22ce28

**Comment by LavellanDWR** [comment]
> Fixed in: [SpikeHD/Vencordorion@e720f0a](https://github.com/SpikeHD/Vencordorion/commit/e720f0a322f0eeecf415214530d6d8ad5e22ce28)

Getting back to this awesome project.
It does process the links correctly in the app now, but still attempts to open them in the browser.
Windows 10, Winget install, version 4.3.0

**Comment by SpikeHD** [comment]
Yea there are still some link issues, it'll likely be tracked in #231
