### ISSUE TITLE
[Feature Request] Remove download app button

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#66]
At the bottom of the server list, there is a button to download the Discord application.
This button comes from 

The solution is to remove the download button.

The button is from discord's website in an effort to make people download their application
![discord download button](https://github.com/SpikeHD/Dorion/assets/91745601/7ae21814-9b1c-49ed-94c6-0df18b661637)
![discord download](https://github.com/SpikeHD/Dorion/assets/91745601/16123ef7-3977-425f-93d9-6d91dad5c982)

**Comment by SpikeHD** [comment]
Added in d488e8b9417e1e0b65a6cd95521ceb34df2f76f7

**Comment by Banaanae** [comment]
Not sure if this needs its own issue but there is one on the top of the screen too
![image](https://github.com/SpikeHD/Dorion/assets/83927639/361544ce-a32a-44e0-a811-20be0252c2ab)
(ik you can close but it could be worth considering)

**Comment by SpikeHD** [comment]
I cannot for the life of me get that to trigger again for some reason, if I manage to I will remove it

**Comment by Temanor** [comment]
I have never had this happen either

**Comment by piotr25691** [comment]
> I cannot for the life of me get that to trigger again for some reason, if I manage to I will remove it

It sometimes appears, other times it doesn't.

Here is that popup's current CSS class: `.notice__5fd4c`

Be aware that removing that will also remove any other notices such as "Security Actions are enabled" or "Streamer Mode is enabled" or "You have gifts in your inventory", etc.
