### ISSUE TITLE
[Bug] Can't open spotify links

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#67]
**Describe the bug**
When clicking on the song title in a Spotify preview, it should open the song page in your browser, but nothing happens.
Instead you need to right click it and press open in new window.

**To Reproduce**
send a link like https://open.spotify.com/track/6A7tNKoqrqH9W6dMPEkLI0
and try to open it

**Expected behavior**
Clicking on the title should open in the web browser or the Spotify app.

**Screenshot**
![spotify preview](https://github.com/SpikeHD/Dorion/assets/91745601/a753b13e-1f6a-440a-92e2-c4e201be7880)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v0.8.0

**Additional context**
I believe the official client opens up the webpage, but I think it would be better if it opened up in the Spotify app instead.

**Comment by Temanor** [comment]
Might be related to #50 ?

**Comment by Temanor** [comment]
clicking the cover art instead of the title will still open up the webpage in a new window

**Comment by SpikeHD** [comment]
Should be fixed in https://github.com/SpikeHD/Vencordorion/commit/08d2446d6f26d7aee9b9b3e11c80ad2934be74e2
