### ISSUE TITLE
Support Vencord

### ISSUE THREAD

**Issue by Liz-chan** [SpikeHD/Dorion#7]
I'm currently using this client mod called Vencord on the official client and it comes with a lot of useful plugins and also lets you use themes kind of how Dorion does it (it loads it from a .css file). I think it'd be good if Vencord could somehow be integrated with Dorion so that I can continue to use those plugins. 

If it makes it any easier, the mod also comes as a browser extension and userscript as well:
https://github.com/Vendicated/Vencord/releases/latest/download/extension.zip
https://github.com/Vendicated/Vencord/releases/download/devbuild/Vencord.user.js

**Comment by SpikeHD** [comment]
The userscript DOES make it easier! First problem I encountered was that Vencord stores it's options in `localStorage` which apparently just isn't a thing:
![image](https://user-images.githubusercontent.com/25207995/202837686-ea29ab6d-2bbb-4d2a-99a1-215256612a18.png)
Seeing as that issue occurs at the end of the script, it's possible Vencord will work fine if the settings are changed to be stored somewhere else, though I have no idea nor am I totally familiar with the project. If you'd like to attempt to fork the project and change that feel free, otherwise it'll be something I look at, but very very low priority.

**Comment by Liz-chan** [comment]
Hm that's pretty strange, Discord stores a lot of things in localStorage so I'm not sure if it could be undefined. I opened a devtools window from the Edge Webview and it was defined on there.

**Comment by SpikeHD** [comment]
Yknow I was just thinking that they did that, how odd. It could probably be rewritten fairly easily to store the configuration into a cookie instead honestly.

**Comment by Liz-chan** [comment]
I found this snippet on SO and it seems like it works:

```js
// If we create an <iframe> and connect it to our document, its
// contentWindow property will return a new Window object with
// a freshly created `localStorage` property. Once we obtain the
// property descriptor, we can disconnect the <iframe> and let it
// be collected — the getter function itself doesn’t depend on
// anything from its origin realm to work**.

function getLocalStoragePropertyDescriptor() {
  const iframe = document.createElement('iframe');
  document.head.append(iframe);
  const pd = Object.getOwnPropertyDescriptor(iframe.contentWindow, 'localStorage');
  iframe.remove();
  return pd;
}

// We have several options for how to use the property descriptor
// once we have it. The simplest is to just redefine it:

Object.defineProperty(window, 'localStorage', getLocalStoragePropertyDescriptor());

window.localStorage.heeeeey; // yr old friend is bak

// You can also use any function application tool, like `bind` or `call`
// or `apply`. If you hold onto a reference to the object somehow, it
// won’t matter if the global property gets deleted again, either.

const localStorage = getLocalStoragePropertyDescriptor().get.call(window);```

**Comment by SpikeHD** [comment]
Added a commit that redefines `window.localStorage` (https://github.com/SpikeHD/Dorion/commit/74957e6b24ce5b32b621c3535921f48d0d9e7767). Have yet to test Vencord but I will some time soon.

**Comment by SpikeHD** [comment]
Good news!

![image](https://user-images.githubusercontent.com/25207995/203214304-94836ecd-8aa7-4dbe-aea6-844c14e8f5bc.png)

So, the gist of the problems I was having, which were plentiful, were that Vencord patches Discord WebPack *as fast as it can*. Like, literally *milliseconds* after the page is navigated to Discord. That becomes a problem with the current plugin system, where plugins are loaded much later into the Discord load cycle.

The solution will be that I will be implementing will be an option for plugins to be labelled as "preload", which means they will be loaded almost instantaneously. Making this optional means that some plugins that depends on Discord being, yknow, loaded, will be fine, and compatibility for outliers like Vencord will also exist.

Expect Vencord to work in the next release 👍

**Comment by SpikeHD** [comment]
Preload plugins are [now a part of Dorion](https://github.com/SpikeHD/Dorion/releases/tag/v0.4.1), which should allow for Vencord to work. If there are issues with it unrelated to the inital injection, please make a new issue instead of re-opening this one :)
