### ISSUE TITLE
[Bug] Empty menus

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#70]
**Describe the bug**
Emojis and stickers and servers don't show up in the emoji menu. You can't select them, either.
The menu for slash commands is also empty.

**To Reproduce**
Open Dorion and click on the emoji to open the emoji menu.
Or type "/" in any chat to open the menu for slash commands.

**Expected behaviour**
You should be able to see all emojis and slash commands and select whichever one you want.

**Screenshots**
![emoji menu](https://github.com/SpikeHD/Dorion/assets/91745601/e8a0455b-5fc2-461e-85e4-568d5ac12c7b)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v0.9.0 (latest)
 - Any other relevant info: Doesn't matter if you use a theme or not.

**Comment by SpikeHD** [comment]
Fixed in 7e896a37be00f49f0630b0c0f87aa45d0ee39215
