### ISSUE TITLE
[Bug] Streamer mode doesn't detect streaming software

### ISSUE THREAD

**Issue by Banaanae** [SpikeHD/Dorion#74]
**Describe the bug**
Dorion doesn't turn on streamer mode when an app (like OBS) is opened

**To Reproduce**
1. Open OBS
2. See streamer mode isn't on

**Expected behavior**
Streamer mode should turn on

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: v0.9.1
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Added in 844e366944ebca646ae33efa00eb8c960ad5bde2 and https://github.com/SpikeHD/Vencordorion/commit/eaf0d639cd874bfb26eb071b62939d043b433ca7
