### ISSUE TITLE
[Feature Request] Desktop notifications

### ISSUE THREAD

**Issue by yavko** [SpikeHD/Dorion#75]
**Is your feature request related to a problem? Please describe.**
The problem is I get pinged and have no idea where it was from

**Describe the solution you'd like**
The desktop notifications toggle to be switchable and for it to work

**Describe alternatives you've considered**
I haven't

**Additional context**
I already know it's on the TODO list found in the readme, it's just I want to be informed when it happens, or maybe I could try implementing it.

**Comment by SpikeHD** [comment]
You are absolutely welcome to try to implement it. To get you started:

* Link to Vencordorion: https://github.com/SpikeHD/Vencordorion
  * You will definitely want to use this to hook into Discord and get when new things that need to be notified are created. You can just create a "dorionNotifications" plugin like how the other functionality is handled.
* Tauri notifications API: https://docs.rs/tauri/latest/tauri/api/notification/struct.Notification.html
  * They also have a JS API for this but I would like to see things like this be put into the Rust backend.
  
If you decide you don't want to do it that's fine, as you've already seen I plan to look into it anyways.

**Comment by yavko** [comment]
> You are absolutely welcome to try to implement it. To get you started:
> 
> * Link to Vencordorion: https://github.com/SpikeHD/Vencordorion
>   * You will definitely want to use this to hook into Discord and get when new things that need to be notified are created. You can just create a "dorionNotifications" plugin like how the other functionality is handled.
> * Tauri notifications API: https://docs.rs/tauri/latest/tauri/api/notification/struct.Notification.html
>   * They also have a JS API for this but I would like to see things like this be put into the Rust backend.
>   
> If you decide you don't want to do it that's fine, as you've already seen I plan to look into it anyways.

Ah thanks, I was wondering on how I would check when new notifications come in. I've never used vencord, so I'll look into the docs tmrw. Though strangely I tried running the notification API (`window.__TAURI__.notifications`) from devtools earlier, but nothing happened, but I bet the rust API will work, if even that doesn't work I'll try a dedicated library.

**Comment by SpikeHD** [comment]
The best "How to make a plugin" guide for Vencord is their [CONTRIBUTING.md](https://github.com/SpikeHD/Vencordorion/blob/main/CONTRIBUTING.md). You can use the other Dorion ones as a reference (I also recco using Chrome + React DevTools for finding components and where to patch them). The workflow is basically:

1. Have Dorion running in dev mode
2. Do whatever in Vencordorion
3. `pnpm buildWeb`
4. Drag `dist/browser.js` into `your_dorion/src-tauri/injection` and replace when prompted
5. Dorion will relaunch automatically

**Comment by yavko** [comment]
> The best "How to make a plugin" guide for Vencord is their [CONTRIBUTING.md](https://github.com/SpikeHD/Vencordorion/blob/main/CONTRIBUTING.md). You can use the other Dorion ones as a reference (I also recco using Chrome + React DevTools for finding components and where to patch them). The workflow is basically:
> 
>     1. Have Dorion running in dev mode
> 
>     2. Do whatever in Vencordorion
> 
>     3. `pnpm buildWeb`
> 
>     4. Drag `dist/browser.js` into `your_dorion/src-tauri/injection` and replace when prompted
> 
>     5. Dorion will relaunch automatically
> 
> 
> Their Rust API should definitely work, only add an external lib is absolutely required :)

cant get it to open, dev tools also just dont appear in dorion
![image](https://github.com/SpikeHD/Dorion/assets/15178513/939079df-5d73-4872-a79b-9127ebc143d8)

**Comment by SpikeHD** [comment]
You'll have to ctrl-shift-i for devtools

**Comment by yavko** [comment]
> You'll have to ctrl-shift-i for devtools

I did that, it dont appear
![image](https://github.com/SpikeHD/Dorion/assets/15178513/a0b1d6fb-30b3-4e16-938b-21bbcae236d2)

**Comment by SpikeHD** [comment]
Oh, no, you won't see React DevTools in the Dorion devtools. Only in a browser like Chrome. You look for what you want to patch in Chrome (the Firefox version doesn't detect Discords React), then replicate that in Vencordorion, then build and transfer `browser.css` and `browser.js` into `src-tauri/injection`

**Comment by yavko** [comment]
> Oh, no, you won't see React DevTools in the Dorion devtools. Only in a browser like Chrome. You look for what you want to patch in Chrome (the Firefox version doesn't detect Discords React), then replicate that in Vencordorion, then build and transfer `browser.css` and `browser.js` into `src-tauri/injection` which is how you test.

Okay time to test in edge then, i dont wanna install another browser lol

**Comment by SpikeHD** [comment]
I mean, with something like notifications you probably won't *really* ***need*** React DevTools, it's just a nice-to-have

**Comment by yavko** [comment]
I think i found the function
![image](https://github.com/SpikeHD/Dorion/assets/15178513/94c2df77-9d8e-4b36-895c-2125ff448993)

**Comment by SpikeHD** [comment]
Certainly looks like it does... something!

**Comment by SpikeHD** [comment]
Added in https://github.com/SpikeHD/Vencordorion/commit/59ab3d7e39827954c06e2d0a4ae3497d808b4fa1

**Comment by yavko** [comment]
> Added in [SpikeHD/Vencordorion@59ab3d7](https://github.com/SpikeHD/Vencordorion/commit/59ab3d7e39827954c06e2d0a4ae3497d808b4fa1)

damn was it really that easy?

**Comment by yavko** [comment]
I had exams this week and couldnt work on it :(

**Comment by SpikeHD** [comment]
> damn was it really that easy?

Lol pretty much. To make them  better I'll need to do more complex stuff but for now it works

> I had exams this week and couldnt work on it :(

All good! Hope exams went well 👍

**Comment by yavko** [comment]
doesn't work for me :P

**Comment by yavko** [comment]
My method was going to do what you did, and replace the discord client code that creates a notification to one that is called from rust `window.__TAURI__.invoke("send_notification", {})`. Problem was I couldn't find where that was called

**Comment by yavko** [comment]
just found it....
```js
showNotification:function(e,t,n,i){var s=arguments.length>4&&void 0!==arguments[4]?arguments[4]:{};r.Z.dispatch({type:"NOTIFICATION_CREATE",icon:e,title:t,body:n,trackingProps:i,options:a(o({},s),{onClick:function(){var e;null===(e=s.onClick)||void 0===e||e.call(s);r.Z.dispatch({type:"NOTIFICATION_CLICK"})}})})}
```

**Comment by yavko** [comment]
> just found it....
> 
> ```js
> showNotification:function(e,t,n,i){var s=arguments.length>4&&void 0!==arguments[4]?arguments[4]:{};r.Z.dispatch({type:"NOTIFICATION_CREATE",icon:e,title:t,body:n,trackingProps:i,options:a(o({},s),{onClick:function(){var e;null===(e=s.onClick)||void 0===e||e.call(s);r.Z.dispatch({type:"NOTIFICATION_CLICK"})}})})}
> ```

Idk if Tauri's notification API can be used, cuz I don't remember seeing anything about handlers

**Comment by yavko** [comment]
> > just found it....
> > ```js
> > showNotification:function(e,t,n,i){var s=arguments.length>4&&void 0!==arguments[4]?arguments[4]:{};r.Z.dispatch({type:"NOTIFICATION_CREATE",icon:e,title:t,body:n,trackingProps:i,options:a(o({},s),{onClick:function(){var e;null===(e=s.onClick)||void 0===e||e.call(s);r.Z.dispatch({type:"NOTIFICATION_CLICK"})}})})}
> > ```
> 
> Idk if Tauri's notification API can be used, cuz I don't remember seeing anything about handlers

Yeah, but the library `notify_rust`, that tauri uses under the hood can be used, as it provides this behaviour

**Comment by SpikeHD** [comment]
Do notifications not work for you already? They work fine for me since that release:
![image](https://github.com/SpikeHD/Dorion/assets/25207995/62c25391-ccfe-4e3b-8893-efd96ccdd384)

**Comment by SpikeHD** [comment]
Try clearing webdata from the Performance & Extras menu and trying to enable them again, I think it's just a user permissions thing

**Comment by SpikeHD** [comment]
Oh also that doesn't mean I'm opposed to having an inbuilt Rust based solution, I just want to make sure it's worth doing first. So far nobody else has complained about notifications so I'm wondering if it's just a minority of people that just need to clear cache

**Comment by yavko** [comment]
> Try clearing webdata from the Performance & Extras menu and trying to enable them again, I think it's just a user permissions thing
> 

I uninstalled webview2 recently, and that cleared permissions
