### ISSUE TITLE
[Bug] Dorion does not inject after recovering from OUT_OF_MEMORY soft crash

### ISSUE THREAD

**Issue by PythonTryHard** [SpikeHD/Dorion#76]
**Describe the bug**
Dorion does not inject after recovering from an `OUT_OF_MEMORY` error by forcing a reload with <kbd>Ctrl</kbd>-<kbd>R</kbd>

**To Reproduce**
1. Start Dorion (optionally join a VC, see Additional context)
2. Boot up something heavy to consume RAM
3. Hope that Dorion OoMs and soft crashes (the Discord client crash, Dorion still running)
4. <kbd>Ctrl</kbd>-<kbd>R</kbd>

**Expected behavior**
Vencord and everything is injected normally

**System Info (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Version: 22H2 (build number `22621.1992`)
 - Affected version: 0.9.1

**Additional context**
1. VC is probably coincidental, because I have left it running overnight several times, no OoM whatsoever.

**Comment by SpikeHD** [comment]
From what I know, there is only so much I do in terms of recovery from outlier problems like this, and seeing as this is probably a fairly rare occurrence with an easy fix of just fully restarting Dorion, I don't see myself ever having the bandwidth to test and mess with this.
