### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [SpikeHD/Dorion#77]
Features I think should be in Dorion: 

- Discord Voice call in tray. (Its in the base discord client and shows microphone activity) (also allow mute and deafen on context menu for dorion icon.)
![image](https://github.com/SpikeHD/Dorion/assets/105545224/c039a666-a4e3-4866-8462-df919e221750)
![image](https://github.com/SpikeHD/Dorion/assets/105545224/f69292db-5d85-40b9-84d5-e10804db90a9)

- Improve the GUI for screen sharing
Dorion: ![image](https://github.com/SpikeHD/Dorion/assets/105545224/a614a321-dcf9-416f-80b2-dabc1a15d159)
Discord: ![image](https://github.com/SpikeHD/Dorion/assets/105545224/02a86c48-3a5b-485b-920a-39aa484da52d)

- Make Discord Key binds work. (Dorion is _technically_ seen as browser discord and docent have functionality for key binds)
![image](https://github.com/SpikeHD/Dorion/assets/105545224/14c25339-7451-411e-9dfc-50cce1d61f46)

- Discord RPC / Game Activity tab like in the original discord client.
![image](https://github.com/SpikeHD/Dorion/assets/105545224/e256cbfc-2e30-41a4-b458-af75511ce753)

- ~Add windows xp support~ 
BUGS: 
- Pings do not display if Dorion is pinned to the TaskBar
- Screen shares occasionally don't work. The screen keeps flickering and sometimes don't load. also audio doesn't load/work sometimes.

**Comment by SpikeHD** [comment]
Please make one issue per feature request, not all at once! Makes it easier for me to track that way.

Also:
> Make Discord Key binds work.

Already has an issue, see #39.

> Improve the GUI for screen sharing

I have no control over this UI as far as I'm aware.

> Discord RPC / Game Activity tab like in the original discord client.

Already available with the `arRPC` plugin enabled and an arRPC server running. This also already has an issue, see #13 

> Pings do not display if Dorion is pinned to the TaskBar

Already has an issue, see #68.

You are welcome to create *separate* issues for anything I didn't mention above.

**Comment by SpikeHD** [comment]
(And please use the issue templates when you do)
