### ISSUE TITLE
[Bug] Stuck on white screen on startup, v0.9.1, Arch

### ISSUE THREAD

**Issue by lkjtigeve** [SpikeHD/Dorion#79]
**The bug**
Dorion doesn't start, shows white window.

**To Reproduce**
Install dorion-bin from the AUR on a fresh Arch installation, start Dorion.

**Expected behavior**
Start up normally.

**System Info:**
 - OS: Latest Arch
 - Version: v0.9.1 

**Terminal dump**
`$ dorion
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
Proxy server listening on port 8678
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
No local config file found. Using default.
JS context not ready...
JS context not ready...
JS context not ready...
JS context not ready...
JS context not ready...
JS context not ready...
JS context not ready...
JS context not ready...
JS context ready!
No local plugin dir found. Using default.
Injecting...
No local config file found. Using default.
No local config file found. Using default.
No local plugin dir found. Using default.
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:3721): GLib-GObject-CRITICAL **: 14:37:10.872: invalid (NULL) pointer instance

(WebKitWebProcess:3721): GLib-GObject-CRITICAL **: 14:37:10.872: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:3721): GLib-GObject-CRITICAL **: 14:37:10.908: invalid (NULL) pointer instance

(WebKitWebProcess:3721): GLib-GObject-CRITICAL **: 14:37:10.908: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed`

**Comment by SpikeHD** [comment]
Not a solution, but I would like to know if more recent versions are what are causing this issue. Do you mind giving [v0.7.4](https://github.com/SpikeHD/Dorion/releases/tag/v0.7.4) a try?

Lemme know if it does the same thing. If not, maybe try experimenting with newer version incrementally til it breaks, and let me know which version that is.

**Comment by SpikeHD** [comment]
Also, DevTools output would be helpful!

**Comment by SpikeHD** [comment]
Closing due to lack of response.

**Comment by MegaRak64** [comment]
`export WEBKIT_DISABLE_COMPOSITING_MODE=1` fixes this problem on NVIDIA GPUs ([webkitgtk problem](https://bugs.webkit.org/show_bug.cgi?id=180739))
