### ISSUE TITLE
[Bug] Voice Chat is not functional when app is out of focus.

### ISSUE THREAD

**Issue by Dappermang** [SpikeHD/Dorion#80]
**Describe the bug**
When trying to use PTT or Voice Activity, Dorion will not transmit your voice.

**To Reproduce**
1. Speak while tabbed out of the application.
2. You will not transmit

**Expected behavior**
My voice needs to be heard!!!

**Screenshots**
NA

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: v1.0.0

**Additional context**
The voice activity icon will still appear active when you are talking or using PTT, but it will still not actually transmit anything.

**Comment by SpikeHD** [comment]
I've encountered this while switching from PTT to Voice Activity while actively in a call, but that's about it. Both PTT and activity work fine, so unless others are able to repro, I'll close this for now
