### ISSUE TITLE
[Bug] Dorion crash when "AlwaysTrust" plugin is installed

### ISSUE THREAD

**Issue by Dysta** [SpikeHD/Dorion#81]
**Describe the bug**
When you install the plugin AlwaysTrust, Dorion is unable to start.

**To Reproduce**
Install the plugin AlwaysTrust and restart Dorion

**Expected behavior**
Dorion should start correctly

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/25008828/25a2ad38-4a78-46be-a1b8-7d0212a27ce4)
![image](https://github.com/SpikeHD/Dorion/assets/25008828/d0f89f65-007d-49d5-b977-88a8a82b8d19)

**System Info (please complete the following information):**
 - OS: W10
 - Version: 1.0.0
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Fixed in https://github.com/SpikeHD/Vencordorion/commit/6f315b1b89fb9447dd08ac010ca9ca3b60aed8fd
