### ISSUE TITLE
[Bug] Stream crashing when system audio is shared

### ISSUE THREAD

**Issue by Yarpopcat08** [SpikeHD/Dorion#82]
**Describe the bug**
The stream crashes in any voice call (server or private). When trying to stream the whole screen with audio the stream just stops. When streaming without audio, the stream goes okay. This bug didn't occure in version 0.9 on Windows 11. The screen and audio were streamed.

**To Reproduce**
Try streaming the whole screen with and tick "Share system audio" . The stream stops

**Expected behavior**
The stream should work, and the system audio should be streamed as well. 

**Screenshots**
Will try add a video later

**System Info:**
 - OS: Windows 11
 - Version: 2H22 22621.2134
 - Dorian version: 1.0

**Additional context**
At the time of posting I can't add anything more.

**Comment by SpikeHD** [comment]
Sometimes I notice I have to restart the stream once every time I start one, which will usually make it work. Try doing:

1. Start a stream
2. It crashes
3. "Change Windows" from Discord stream menu
4. Change to the exact same thing you were already streaming
5. It should restart and work

**Comment by Yarpopcat08** [comment]
Well, I just tried to stream, and discord even fails to show the "Choose what window you want to stream" dialog. Interesting

**Comment by SpikeHD** [comment]
Can't really reproduce this, closing
