### ISSUE TITLE
[Feature Request] Change Vencord's message logger with enhanced version

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#83]
**Is your feature request related to a problem? Please describe.**
No. The message logger works just fine. The enhanced version is just better.

**Describe the solution you'd like**
I would like to see the message logger in Vencord plugins page to be replaced with [Message Logger Enhanced](https://github.com/Syncxv/vc-message-logger-enhanced)

**Describe alternatives you've considered**
Add the enhanced version as an alternative plugin within the plugins page

**Additional context**
Features:
Restore deleted and edited messages even after reloading Discord (optional).
Log messages from channels or DMs you haven't opened.
View logs in a modal that shows your logged messages.
Sort messages based on timestamps.
Search logs by channel ID, user ID, server ID, and message ID.
Ghost Pinged tab to track and view ghost pings.
Set a message limit to manage the number of saved logs (settings).
Blacklist servers, channels, and users to prevent logging specific content.
Whitelist feature to selectively allow logging for specific servers, channels, or users.
Whitelist overrides server blacklist, allowing logging of whitelisted users' actions in blacklisted servers and channels.
Export logs for backup and analysis purposes.
Import logs to restore previous logging data.

**Comment by SpikeHD** [comment]
I don't think I will be doing this for a couple reasons:
* There is no easy way to compile a Vencord plugin by itself. It must be compiled by adding the plugins folder to a clone of vencord, and compiling Vencord fully.
* I don't feel great about storing logs indefinitely, nor do a lot of other people (see [the discussions in the thread about it in the Vencord discord](https://ptb.discord.com/channels/1015060230222131221/1131677805550252092/1131686706932895774))

If you would still like to use this plugin (or other plugins not included by default), you can follow along with the video guide in the repo you linked. Just remember to [use my fork](https://github.com/SpikeHD/Vencordorion) and not the main repo, or else you'll lose lots of Dorion functionality :P
