### ISSUE TITLE
[Feature Request] Add dorion version to settings page

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#84]
**Is your feature request related to a problem? Please describe.**
Not really. You mentioned that the top bar was themable, meaning the Dorion version could be changed with a theme.
Having the Dorion version in the settings page just kinda makes sense.

**Describe the solution you'd like**
Add Dorion version number to the bottom of the settings page.

**Additional context**
![image](https://github.com/SpikeHD/Dorion/assets/91745601/01b47cf2-a65f-47d8-9670-8c39b2668a56)

**Comment by SpikeHD** [comment]
Added in https://github.com/SpikeHD/Vencordorion/commit/c957a6b892719a7019a485945b7b9b2cb6a2ca13
