### ISSUE TITLE
[Feature Request] Make the "Open" from the taskbar menu icon put Dorion's window on top.

### ISSUE THREAD

**Issue by LunnerB** [SpikeHD/Dorion#85]
**Is your feature request related to a problem? Please describe.**
Not really, just a thing that I'm used to from Discord client.

**Describe the solution you'd like**
When you use the "Open" button from Dorion taskbar icon it shows/put the window on top.

**Describe alternatives you've considered**
If not possible maybe just make the Dorion tab flash on taskbar, who knows...

**Additional context**
![image](https://github.com/SpikeHD/Dorion/assets/71968746/b2336dac-7edc-4ced-81f9-ad0483353dee)

**Comment by SpikeHD** [comment]
Added in 5f258614f67689daa7c741feb35f1ecc39f49229
