### ISSUE TITLE
[Bug] Search result link behaviour

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#88]
**Describe the bug**
When clicking links in the search result, Dorion opens up a new window with the page instead of opening it in the browser.

**To Reproduce**
Search for something in a discord server.
Find a message in the search result containing a link.
Press the link.

**Expected behavior**
The link should be opened in the browser as all other links are.

**Screenshots**
![Screenshot 2023-09-06 085158](https://github.com/SpikeHD/Dorion/assets/91745601/20665061-9237-42bb-ad2b-d8231ac83569)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.1.0
 - Any other relevant info:  :)

**Additional context**
As far as I can tell, all other links open correctly.

**Comment by SpikeHD** [comment]
Should be fixed in 4c44d8d and will be available in the next release!
