### ISSUE TITLE
[Bug] Discord crashes (maybe because of update)

### ISSUE THREAD

**Issue by electricsteve** [SpikeHD/Dorion#94]
**Describe the bug**
Discord crashes on startup. My friend uses normal vencord and needed to update his discord, maybe this is the problem?

**To Reproduce**
1. Start Dorion

**Expected behavior**
SHould just start

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/96793824/c55a1a21-bb0e-4f77-9f0f-32868ce17a91)
Sorry for the flashbang

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: V.1.1.0
 - Any other relevant info: On school wifi.

**Additional context**
Wanted to start my dorion.

**Comment by SpikeHD** [comment]
Are you using the “blurnsfw” plugin by any chance?

**Comment by electricsteve** [comment]
I probably am

**Comment by electricsteve** [comment]
Is there a way to jsut disable that plugin? I dont want  to lose settings

**Comment by electricsteve** [comment]
where's the logs in devtools?

**Comment by SpikeHD** [comment]
Hit the “Console” tab, there will probably be logs like “Plugin XYZ encountered an error!”. I wanna know what plugin so I can fix/watch for a fix

**Comment by electricsteve** [comment]
<img width="959" alt="image" src="https://github.com/SpikeHD/Dorion/assets/96793824/2d1f70a9-1e00-48ed-99e0-ca36500a9e55">
![image](https://github.com/SpikeHD/Dorion/assets/96793824/3208f467-60db-4831-a283-c38d7730da03)
Only the errors

**Comment by SpikeHD** [comment]
Yea okay thats the NSFW blur plugin. You’ll just want to wipe the profile and not reenable the plugin til its fixed unfortunately

**Comment by electricsteve** [comment]
fudge

**Comment by SpikeHD** [comment]
Closing as there are now temp fixes/workarounds for this sort of thing (see: the new args in 1.2.0)
