### ISSUE TITLE
[Feature Request] please don't pollute my home directory

### ISSUE THREAD

**Issue by colemickens** [SpikeHD/Dorion#95]
**Is your feature request related to a problem? Please describe.**

Not sure if I'm doing something wrong, but I have about 4 directories in my home directory, two of which are actually symlinks. I have a big pet peeve against things getting dumped into my home directory -- usually it's random dot-files or dot-dirs, but Dorion is even more bold -- it creates a regularly named `~/dorion` folder.

**Describe the solution you'd like**

* It not to do this, especially since I don't have any plugins.
* Follow XDG dirs and use `XDG_DATA_HOME` or `XDG_CONFIG_HOME` or `XDG_STATE_HOME` as appropriate.

**Describe alternatives you've considered**
* n/a

**Additional context**
* n/a

Thank you for Dorion!

**Comment by SpikeHD** [comment]
Lol yea I've been meaning to change this up, you should hopefully see it changed in the next release

**Comment by SpikeHD** [comment]
This should be fixed in 4a16e1525c69677fcad2d101e3dcc703d2fff70b and will be available in the next release 👍
