### ISSUE TITLE
[TODO] ARM builds

### ISSUE THREAD

**Issue by SpikeHD** [SpikeHD/Dorion#96]
Implementing ARM builds in Actions soon, just need this to remind myself

**Comment by Wuemeli** [comment]
Reminderrrrr

**Comment by SpikeHD** [comment]
@Wuemeli if you are in need and don't want to wait, you can always [build Dorion yourself](https://github.com/SpikeHD/Dorion#building) 👍

**Comment by SpikeHD** [comment]
Windows ARM builds are now real: https://github.com/SpikeHD/Dorion/actions/runs/8827174375/job/24234026533

Now we just have to fix ARM Linux builds and we're all set

**Comment by SpikeHD** [comment]
Took me long enough (see 73f58d3c2f7ef117607ff46e017f22f398d93827)

Thank you to myself for figuring this out for [RogueTop](https://github.com/SpikeHD/RogueTop) first.

**Comment by rubenbbrp** [comment]
where are the ARM builds? the link in the main page is no working to download ARM build

**Comment by SpikeHD** [comment]
@rubenbbrp you can find a download for every build in the [Releases](https://github.com/SpikeHD/Dorion/releases/tag/v6.10.0) page
