### ISSUE TITLE
[Feature Request] Shelter Client Injection

### ISSUE THREAD

**Issue by RavenCutie21** [SpikeHD/Dorion#97]
**Is your feature request related to a problem? Please describe.**
no, just an alternative mod that is meant to be future proof. 

**Describe the solution you'd like**
Shelter is a future proof client mod, doesn't have many plugins currently but it is starting to pick up. 

**Additional context**
In the future if Discord ever nukes client mods again, Shelter should theoretically still be standing, as it is vastly different to other cli mods and doesn't poke at similar stuff. uwu/shelter

**Comment by SpikeHD** [comment]
Neat!

![image](https://github.com/SpikeHD/Dorion/assets/25207995/60b9f7e7-4326-4a46-8cf5-f35f941b0ed8)

This won't fetch plugins via link properly without some small modifications, but you can [download shelter.js](https://raw.githubusercontent.com/uwu/shelter-builds/main/shelter.js), place that into your Dorion plugins folder, set it as a preload plugin, and load plugins by Copy-pasting their contents as a "Local plugin" (assuming it's easily copy-paste-able).

If there is lots of interest (and I mean, like, more than one person wanting this) in supporting Shelter fully I may consider building a modified Dorion-specific version, potentially even as a full alternative to the current Vencordorion backend.

**Comment by SpikeHD** [comment]
Shelter now unofficially works (with plugin URLs!) as of 6b43acd57951433914e8c6ef0c33240c801ccbb7!

![image](https://github.com/SpikeHD/Dorion/assets/25207995/44912d56-54b8-4ebf-923f-2bacab9fdd4d)
![image](https://github.com/SpikeHD/Dorion/assets/25207995/00b15519-a697-469a-b679-c913da8ef174)

This may have some unforeseen issues, but for the most part, from my testing, it works just fine. This will be available in the next release 👍 

And if someone wants, they can make a Dorion settings plugin for Shelter by reading how the [Vencordorion](https://github.com/SpikeHD/Vencordorion/) settings frontend communicates with the Dorion backend to replicate.

**Comment by Temanor** [comment]
After downloading shelter and trying to enter the shelter settings, I get the "Discord has crashed. attempting to recover" message.
Discord behaves normally even though it says it crashed. It's just the shelter settings page that doesn't open.

**Comment by SpikeHD** [comment]
Is it set to preload? It works fine for me
<img width="708" alt="image" src="https://github.com/SpikeHD/Dorion/assets/25207995/c3f6c5b6-3ec5-428d-ba64-38f20a7f168b">
<img width="751" alt="image" src="https://github.com/SpikeHD/Dorion/assets/25207995/02d98d88-f1a3-44b6-8684-16370996e1a1">

**Comment by Temanor** [comment]
I thought for sure I did, but I guess it didn't get saved?
Anyway, I enabled it again and now it works.
