### ISSUE TITLE
[Bug] Forms don't work

### ISSUE THREAD

**Issue by Banaanae** [SpikeHD/Dorion#99]
**Describe the bug**
Forms are what allow some discord bots to work (like Tickets bot)

**To Reproduce**
1. Add [Tickets bot](https://ticketsbot.net/) to a server
2. Set it up in a way where forms is required to make a ticket
3. Click the button and get an error (see screenshots)

**Expected behavior**
A form like this should appear
![19qpes195sg81-1680854427](https://github.com/SpikeHD/Dorion/assets/83927639/0b1867d3-4b9f-4eaf-9fa0-42c55cb9a7df)

**Screenshots**
When pressing the button that should open the form
![image](https://github.com/SpikeHD/Dorion/assets/83927639/70e329e7-cd6e-41a4-8ea0-5bff9c69d797)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.2.0
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Fixed in https://github.com/SpikeHD/Vencordorion/commit/86f539ec53bc2b64886fb09183563766b32c087e and will be available in the next release
